### ISSUE TITLE
BUILD_SHARED_LIBS=OFF does not disable building shared libraries on Ubuntu

### ISSUE THREAD

**Issue by drtimes** [GrokImageCompression/grok#102]
[user: build]$ cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_CODEC=OFF -DBUILD_PKGCONFIG_FILES=OFF ..
...
[user: build]$ make
[user: build]$ cd bin
[user: bin]$ ls
libopenjp2.a         libopenjp2.so        libopenjp2.so.7
libopenjp2_plugin.a  libopenjp2.so.2.2.0

Checking seems to be done only for WIN32
https://github.com/GrokImageCompression/grok/blob/master/src/lib/openjp2/CMakeLists.txt#L136

**Comment by boxerab** [comment]
It's actually a feature :)  On Unix, both shared and static libs are built. But, the compress and decompress binaries are linked either statically or dynamically depending on setting of this flag. I guess we could change the name to `LINK_SHARED`, for example.

**Comment by boxerab** [comment]
I think, for backwards compatibility, I will not change the name. But, will update the wiki.

**Comment by boxerab** [comment]
Alright, I have updated the wiki with a clarification on this. Thanks for reporting.

**Comment by boxerab** [comment]
Correction: updated the INSTALL.md file.
