### ISSUE TITLE
Decoding region produces wrong pixel values

### ISSUE THREAD

**Issue by drtimes** [GrokImageCompression/grok#107]
Hello, Aaron!

I've found a bug when decoding a specific region of a Sentinel-2 image. The application does not crash, but produces values that are partially incorrect (the first row).

$ ./opj_decompress -i B01.jp2 -o ar.tif -NumThreads 1 -r 0 -d 1254,1013,1266,1024
The image I used: http://sentinel-s2-l1c.s3.amazonaws.com/tiles/36/U/XU/2016/7/31/0/B01.jp2
Output array:
3354 3353 3351 3351 3351 3352 3352 3353 3347 3344 3342 3344 
1505 1508 1508 1507 1506 1504 1504 1500 1498 1500 1499 1498 
1507 1503 1509 1509 1509 1510 1508 1502 1501 1503 1499 1502 
1507 1505 1508 1508 1509 1513 1507 1503 1504 1505 1503 1499 
1516 1520 1511 1510 1508 1509 1506 1503 1506 1507 1501 1497 
1513 1514 1511 1513 1510 1508 1505 1500 1502 1503 1504 1499 
1523 1521 1519 1514 1514 1508 1506 1502 1504 1504 1503 1501 
1529 1527 1524 1519 1517 1512 1513 1511 1509 1508 1511 1506 
1524 1522 1522 1518 1510 1509 1512 1514 1513 1513 1514 1510 
1523 1518 1518 1515 1509 1507 1512 1514 1510 1509 1511 1510 
1522 1519 1517 1518 1508 1508 1511 1513 1509 1508 1508 1508 

Built from branch master, rev number 7f664f2577a4b88b40dc7cf0114236f8e1334c58, cmake options: -DBUILD_THIRDPARTY=ON. It also reproduces in v2.3.0 (I didn't try the versions < 2.3.0)

Another example:
$ ./opj_decompress -i B10.jp2 -o ar2.tif -NumThreads 1 -r 0 -d 1130,969,1142,981
The image I used: http://sentinel-s2-l1c.s3.amazonaws.com/tiles/36/U/XU/2016/7/31/0/B10.jp2
Output array:
[[1803 1804 1804 1805 1802 1801 1801 1801 1802 1801 1801 1802]
 [  13   13   13   13   13   13   12   11   10   11   11   12]
 [  11   13   13   12   14   13   13   11   11   13   13   13]
 [  11   13   14   13   11   11   13   12   12   12   11   13]
 [  11   14   15   15   14   12   13   14   11   11   11   13]
 [  13   13   14   12   12   13   13   13   11   12   13   12]
 [  13   12   12   11   12   13   12   12   11   11   12   13]
 [  13   13   13   15   13   13   13   12   11    9   12   13]
 [  12   11   13   14   12   13   12   11   12   10   13   13]
 [  12   10   12   13   13   13   14   13   13   13   12   12]
 [  13   12   13   13   11   14   14   13   11   13   12   12]
 [  12   12   12   11   12   12   10   13   11   12   12   12]]

Regards,
Kate

**Comment by boxerab** [comment]
Thanks for reporting this. Yes, clearly the first row is greater than 15 bit precision, so incorrect.
I will investigate.

**Comment by boxerab** [comment]
So, I see you are setting the `-r` parameter to 0.  i.e. you are reducing the number of resolutions by 0.
Can you try this without the `-r` parameter and see if it is still giving incorrect results ?

**Comment by boxerab** [comment]
Never mind, the problem is that the library is calculating a height of 11 pixels, when it should be 12.

**Comment by boxerab** [comment]
Can you please tell me how you are reading back the pixel values ?

**Comment by boxerab** [comment]
Also, what OS are you using ?

**Comment by drtimes** [comment]
My OS is Ubuntu 14.04, processor Intel® Core™ i3-4170 CPU @ 3.70GHz × 4
Compiler
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

Removing -r parameters didn't help. 
To read the image I use GDAL 2.1.0 python bindings.

$ ./opj_decompress -i B01.jp2 -o ar.tif -NumThreads 1 -d 1254,1013,1266,1024
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal, gdal_array
>>> ds = gdal.Open('ar.tif')
>>> img = gdal_array.DatasetReadAsArray(ds)
>>> print img
[[3354 3353 3351 3351 3351 3352 3352 3353 3347 3344 3342 3344]
 [1505 1508 1508 1507 1506 1504 1504 1500 1498 1500 1499 1498]
 [1507 1503 1509 1509 1509 1510 1508 1502 1501 1503 1499 1502]
 [1507 1505 1508 1508 1509 1513 1507 1503 1504 1505 1503 1499]
 [1516 1520 1511 1510 1508 1509 1506 1503 1506 1507 1501 1497]
 [1513 1514 1511 1513 1510 1508 1505 1500 1502 1503 1504 1499]
 [1523 1521 1519 1514 1514 1508 1506 1502 1504 1504 1503 1501]
 [1529 1527 1524 1519 1517 1512 1513 1511 1509 1508 1511 1506]
 [1524 1522 1522 1518 1510 1509 1512 1514 1513 1513 1514 1510]
 [1523 1518 1518 1515 1509 1507 1512 1514 1510 1509 1511 1510]
 [1522 1519 1517 1518 1508 1508 1511 1513 1509 1508 1508 1508]]

**Comment by drtimes** [comment]
After the fix 7d6c08743e20aee3d2130748472444fc0496661e the error is gone. Thank you!

**Comment by boxerab** [comment]
Glad to hear. Thanks again for opening the issue.
