### ISSUE TITLE
Install on Ubuntu 17.10 failed?

### ISSUE THREAD

**Issue by symac** [GrokImageCompression/grok#125]
I discovered this tool following a comment by @boxerab on uclouvain/openjpeg#1058 and am hoping to fix an issue I have with uclouvain/openjpeg regarding the way it deals with ICC profiles (original issue with examples files on uclouvain/openjpeg#1040).

But so far I have been able to install the tool, even starting with a blank system (Ubuntu 17.10 in a new virtualbox). 

Here is what I have done so far: 

- sudo apt install git
- mkdir JP2
- cd JP2
- git clone https://github.com/GrokImageCompression/grok.git
- mkdir grok_build
- cd grokbuild
- sudo apt install cmake
- sudo apt install build-essential
- sudo apt install libjpeg-turbo8-dev
- sudo apt install libtiff5-dev
- cmake /home/jp2/JP2/grok
- sudo make install

Starting from there I get errors. The first one was : 
```
/home/jp2/JP2/grok/src/bin/jp2/opj_decompress.cpp: In function â€˜int plugin_main(int, char**, DecompressInitParams*)â€™:
/home/jp2/JP2/grok/src/bin/jp2/opj_decompress.cpp:1371:15: error: â€˜UINT_MAXâ€™ was not declared in this scope
     seconds = UINT_MAX;
               ^~~~~~~~
```
I (badly) fixed it by replacing the constant UINT_MAX with a fixed value. But starting again the make install I get another error and suspect something is wrong with the way I am trying to run the software. The error I now get is:
```
[ 87%] Building C object src/bin/jp2/CMakeFiles/opj_decompress.dir/iccjpeg.c.o
[ 88%] Linking CXX executable ../../../bin/opj_decompress
CMakeFiles/opj_decompress.dir/opj_decompress.cpp.o: In function `post_decode(grok_plugin_decode_callback_info*)':
opj_decompress.cpp:(.text+0x8401): undefined reference to `color_cielab_to_rgb(opj_image*, bool)'
collect2: error: ld returned 1 exit status
src/bin/jp2/CMakeFiles/opj_decompress.dir/build.make:436: recipe for target 'bin/opj_decompress' failed
make[2]: *** [bin/opj_decompress] Error 1
CMakeFiles/Makefile2:353: recipe for target 'src/bin/jp2/CMakeFiles/opj_decompress.dir/all' failed
make[1]: *** [src/bin/jp2/CMakeFiles/opj_decompress.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

Is there an issue with the master or is this because of the way I am trying to install things?
```

**Comment by symac** [comment]
I have been able to pass the issue described above by installing `liblcms2-dev` but now, when i try to run `opj_compress` I get the following error : 
```
opj_compress: symbol lookup error: opj_compress: undefined symbol: opj_image_single_component_data_free
```

**Comment by boxerab** [comment]
Try using cmake-gui and read INSTALL doc. You need to run ldconfig after installing

**Comment by symac** [comment]
Shame on me. I had read the INSTALL doc but had thought that ldconfig was not applying to my case as I had run the make install as sudo. Sorry for bothering you with that, now seems to work fine, thanks for the quick reply.

**Comment by boxerab** [comment]
Np, happy to help. Please let me know if you  have any other issues

**Comment by boxerab** [comment]
@symac I've added the missing header that was causing the initial error. If you have time, would you mind pulling the latest code and checking if the build now works?

**Comment by symac** [comment]
Thanks @boxerab , works fine with the latest code, no more constant error.

**Comment by boxerab** [comment]
Cool, thanks for checking.
