### ISSUE TITLE
Compressing TIF with tiles results in corrupted partial tiles

### ISSUE THREAD

**Issue by jbaiter** [GrokImageCompression/grok#128]
When compressing a 1626x2164 TIF with `-t 1024,1024 -r 10`, the bottom partial tiles are corrupted:

![](https://i.imgur.com/odMPPRN.jpg)

This is with the most recent Git HEAD.
The same image compressed with vanilla OpenJPEG does not have any issues. Unfortunately, I need to retain the ICC info, so I need grok.

You can find the original TIF here: https://transfer.sh/BkeDA/grok_corrupt_tiles.tif (should be up for the next 14 days)

**Comment by boxerab** [comment]
Interesting. Can you test on OPENJPEG If you have time?

**Comment by boxerab** [comment]
Oh, I see you already did.

**Comment by boxerab** [comment]
Can you try 512x512 tiles?

**Comment by boxerab** [comment]
Aldo, try lossless

**Comment by jbaiter** [comment]
512x512 tiles results in the right partial tiles being corrupted.
Lossless does not result in any corruption.

**Comment by jbaiter** [comment]
Fascinating, I just backported the ICC-transfer parts to OpenJPEG (https://github.com/jbaiter/openjpeg/tree/transfer-icc-profiles), and boom, exactly the same behavior in all points:

- Corruption at the bottom with `-r 10 -t 1024,1024`
- Corruption on the right with `-r 10 -t 512,512`
- No corruption with `-r 2` or `-r 1`

Interestingly, I just tried `-r 5` and suddenly the corruption is restricted to the rightmost bottom tile!
So your hunch seems to be right, it looks like it's related to the final file size.

**Comment by boxerab** [comment]
Another data point : setting r to 100 corrupts the entire image.

**Comment by boxerab** [comment]
The ICC profile here is actually quite large: over 300K ! I don't think this is a bug, in fact. When there is rate control with a large header, the code stream will be truncated. This looks like corruption because rate control is throwing away most of the image.

**Comment by boxerab** [comment]
Rate control applies to the entire JP2 file, not just the code stream.

**Comment by boxerab** [comment]
I am going to close this : not in fact a bug.

**Comment by jbaiter** [comment]
Wow, OK, that is unexpected. Intuitively this does not make much sense, rate control should only apply to the actual image data, not the metadata. But if it's in the spec, it's in the spec :man_shrugging:

**Comment by boxerab** [comment]
Actually, it still looks like a bug to me, because if there is rate loss, it should not be concentrated in the final tile, but distributed over all the tiles.

**Comment by jbaiter** [comment]
This is probably not really interesting, but using the `-q` parameter with PSNR values for compression does not cause the bug, so I'll probably use that in the meantime.

**Comment by boxerab** [comment]
Fixed the problem with the `-r` parameter. It was a subtle issue. Let me know if this is working for you.

**Comment by jbaiter** [comment]
Works like a charm, thank you so much!
