### ISSUE TITLE
Tutorial read/write application?

### ISSUE THREAD

**Issue by ahota** [GrokImageCompression/grok#139]
First, thanks for all the work on this library. I have been needing to do some processing using JPEG-2000 images and have so far found other higher level libraries lacking.

However, looking through the documentation and included applications (`grk_dump` and `grk_decompress` in particular), it's difficult to determine what steps are _required_ to read a JP2 file. Reading the header is straightforward enough, for example:

```cpp
int main(int argc, char **argv) {
  grk_dparameters parameters;
  grk_image *image = nullptr;
  grk_codec *codec = nullptr;
  grk_stream *stream = nullptr;

  grk_initialize(nullptr, 0);

  grk_set_default_decoder_parameters(&parameters);

  strncpy(parameters.infile, argv[1], 4096);
  parameters.decod_format = JP2_CFMT;

  stream = grk_stream_create_default_file_stream(parameters.infile, 1);
  codec = grk_create_decompress(GRK_CODEC_JP2);

  if (!grk_setup_decoder(codec, &parameters)) {                    
    std::cout << "failed to setup the decompressor" << std::endl;
    return 1;                                                    
  }
                                                                
  if (!grk_read_header(stream, codec, nullptr, &image)) {         
    std::cout << "failed to read the image header" << std::endl;
    return 1;                                                   
  }                                                               

  // now `image` contains metadata on the JP2 file, such as height/width, num components, etc.

  return 0;
}
```

Much of this was gleaned from `grk_dump`. For the sake of this being a "hello, world" toy application, I've removed most of the flexibility and error-checking from `grk_dump`.

But the jump from reading the header to reading a file seems large. Do I need to start using a plugin? How do the plugins work? Based on `grk_decompress` it seems I need to use `grk_plugin_decode_callback_info` to hold onto metadata, such as tile information. Or is this a more general-purpose approach to demonstrate Grok's capabilities? For a specific or toy application can I just manually hold the data as I am above?

I am ultimately just trying to load a JP2 file into memory to access pixel values from the largest resolution sub-image.

**Comment by boxerab** [comment]
@ahota thanks.  I'm afraid I don't have time to get into much detail about the design. I will say that plugins were designed for hardware accelerators, so you don't need to use them. For decoding, you can look at the `grk_decompress` code to see how it is done. You have to make a few small changes to decode into a memory buffer - look for  bool isBufferStream = false;` and set this to true.  Good Luck !

**Comment by dukesook** [comment]
I'm also interested in a compress/decompress "hello world" example program. I could get this eventually through grk_compress & grk_decompress, but seeing the simplest possible case would be a big timer saver. How hard would it be to throw one together?
