### ISSUE TITLE
covert kodak PNG images into JP2 with sampling factor

### ISSUE THREAD

**Issue by khawar512** [GrokImageCompression/grok#207]
I am trying to convert png images into JP2 with sampling factor. I am imagemagick tool for conversion, as they mentioned in docs -sampling-factor is used for sampling but it did not work.

http://ftp.icm.edu.pl/pub/unix/graphics/ImageMagick/www/jp2.html

convert wizard.png -colorspace YUV -sampling-factor 2,2 wizard.jp2

My command, it did not work
convert test/images/kodim$i.png -quality $(($j*5)) -colorspace YUV -sampling-factor 4,2 test/JP2/kodim$i/printf "%02d" $j.jp2

**Comment by boxerab** [comment]
This is a question for ImageMagick. This is a completely different project.
