### ISSUE TITLE
lossy compression via PSNR fails when opj_compress succeeds

### ISSUE THREAD

**Issue by comstock** [GrokImageCompression/grok#223]
example TIFF: `https://github.com/harvard-library-imaging-services/images/raw/master/lossy_fails/246094.tif`

The above is a difficult image to lossy-compress: lots of uniform sky with detailed figures in foreground.

opj_compress produces a good result via `opj_compress -i ./staging/246094.tif -o ~/Desktop/246094_40.jp2 -t 1024,1024 -I -q 40`

grk_compress fails via `grk_compress -i ./staging/246094.tif -o ~/Desktop/246094_40.jp2 -t 1024,1024 -I -q 40`

I prefer grk_compress because it handles display profiles appropriately, but now I know not to assume that grk and opj produce otherwise similar results.

**Comment by boxerab** [comment]
Thanks for posting. It looks like the ICC profile is corrupt - let me do a little digging and get back to you.

**Comment by boxerab** [comment]
So, this was a serious bug in the compressor, now fixed. It was present for about 8 months, and only affected lossy compression of monochrome imagery. I will be adding unit tests to our continuous integration to cover this use case, as this should have been caught when it was introduced.

The ICC profile is for RGB colour space, but the image is monochrome. Opening in GIMP, the image is bright red. I will add a warning to that effect.

**Comment by boxerab** [comment]
Here is a new release with the fix:

https://github.com/GrokImageCompression/grok/releases/tag/v7.6.6
