### ISSUE TITLE
How to compile ZLIB and JPEG support in TIFF?

### ISSUE THREAD

**Issue by martinhankovec** [GrokImageCompression/grok#24]
Hello,
I have a problem converting some TIFF images to JP2. opj_compress said:
AdobeDeflate compression support is not configured
I have found it can be related to libtiff not having zip support compiled, How can I switch zip support in built-in thirdparty libtiff? Or how can I fixed this error? TIFF image is attached
[image.zip](https://github.com/GrokImageCompression/grok/files/526359/image.zip)
Thanks a lot
Martin

**Comment by boxerab** [comment]
Hi Martin,

Thanks for opening this issue.

For zip support, I have just checked in some provisional support. 
To get zip, you must manually uncomment the line

//#cmakedefine ZIP_SUPPORT

in `tif_config.h.cmake.in`  file

Let me know how that works for you.

Aaron

**Comment by boxerab** [comment]
Martin,
If you pull from master, zlib support for TIFF should just work. Let me know how it goes.
Aaron

**Comment by martinhankovec** [comment]
Hi Aaron,
current master cannot be compiled on Linux CentOS 7:

# make
In file included from /home/install/grok-mh/src/lib/openjp2/opj_includes.h:65:0,
                 from /home/install/grok-mh/src/lib/openjp2/bio.cpp:56:
/home/install/grok-mh/src/lib/openjp2/overflow_utils.h: In function ‘bool grk_mult_will_overflow(uint32_t, uint32_t)’:
/home/install/grok-mh/src/lib/openjp2/overflow_utils.h:25:20: error: ‘UINT_MAX’ was not declared in this scope
  return (b && (a > UINT_MAX / b));
                    ^
/home/install/grok-mh/src/lib/openjp2/overflow_utils.h: In function ‘bool grk_add_will_overflow(uint32_t, uint32_t)’:
/home/install/grok-mh/src/lib/openjp2/overflow_utils.h:29:15: error: ‘UINT_MAX’ was not declared in this scope
  return  (a > UINT_MAX - b);
               ^
make[2]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/bio.cpp.o] Error 1
make[1]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/all] Error 2
make: *** [all] Error 2

**Comment by martinhankovec** [comment]
Hi Aaron,
I have added comment to the issue You have closed - new master cannot be 
compiled (see log in issue).
Martin

Dne 13.10.2016 v 22:16 Aaron Boxer napsal(a):

**Comment by boxerab** [comment]
Sorry, have not built linux version in a while :)
All should be working now.

**Comment by boxerab** [comment]
Closing this issue. Please re-open if you have any problems with zip support for TIFF.

**Comment by martinhankovec** [comment]
Sorry, but still not working:
if I try to compile, compilation goes through OK, but ZIP support not working for image I have sent above:
opj_compress -i snimek_001.tif -o snimek1.jp2
Unable to open library ./libopenjp2_plugin.so

TIFFReadDirectory: Warning, Unknown field with tag 317 (0x13d) encountered.
snimek_001.tif: AdobeDeflate compression support is not configured.
snimek_001.tif: AdobeDeflate compression support is not configured.
Unable to load tiff file

If I try to uncomment
//#cmakedefine ZIP_SUPPORT
in  tif_config.h.cmake.in  file, code cannot be compiled due to huge amount of errors:
```
# make
-- We will build Z lib from thirdparty
-- We will build PNG lib from thirdparty
-- We will build TIFF lib from thirdparty
-- We will build LCMS2 lib from thirdparty
-- Configuring done
-- Generating done
-- Build files have been written to: /home/install/grok-master
[ 22%] Built target openjp2
[ 24%] Built target openjp2_plugin
[ 34%] Built target z
[ 44%] Built target png
Scanning dependencies of target tiff
[ 44%] Building C object thirdparty/libtiff/CMakeFiles/tiff.dir/tif_aux.c.o
In file included from /home/install/grok-master/thirdparty/libtiff/tiffiop.h:33:0,
                 from /home/install/grok-master/thirdparty/libtiff/tif_aux.c:32:
/home/install/grok-master/thirdparty/libtiff/tif_config.h:5:1: error: unknown type name ‘cmakedefine’
 cmakedefine ZIP_SUPPORT
 ^
In file included from /usr/include/fcntl.h:31:0,
                 from /home/install/grok-master/thirdparty/libtiff/tiffiop.h:36,
                 from /home/install/grok-master/thirdparty/libtiff/tif_aux.c:32:
/usr/include/bits/types.h:30:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
 typedef unsigned char __u_char;
 ^
In file included from /home/install/grok-master/thirdparty/libtiff/tiffconf.h:10:0,
                 from /home/install/grok-master/thirdparty/libtiff/tiff.h:30,
                 from /home/install/grok-master/thirdparty/libtiff/tiffio.h:33,
                 from /home/install/grok-master/thirdparty/libtiff/tiffiop.h:66,
                 from /home/install/grok-master/thirdparty/libtiff/tif_aux.c:32:
/home/install/grok-master/thirdparty/libtiff/tif_config.h:5:1: error: unknown type name ‘cmakedefine’
 cmakedefine ZIP_SUPPORT
 ^
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h:9:0,
                 from /home/install/grok-master/thirdparty/libtiff/tiffconf.h:12,
                 from /home/install/grok-master/thirdparty/libtiff/tiff.h:30,
                 from /home/install/grok-master/thirdparty/libtiff/tiffio.h:33,
                 from /home/install/grok-master/thirdparty/libtiff/tiffiop.h:66,
                 from /home/install/grok-master/thirdparty/libtiff/tif_aux.c:32:
/usr/include/stdint.h:48:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘typedef’
 typedef unsigned char  uint8_t;
 ^
In file included from /home/install/grok-master/thirdparty/libtiff/tiffio.h:33:0,
                 from /home/install/grok-master/thirdparty/libtiff/tiffiop.h:66,
                 from /home/install/grok-master/thirdparty/libtiff/tif_aux.c:32:
/home/install/grok-master/thirdparty/libtiff/tiff.h:69:1: error: unknown type name ‘uint8_t’
 typedef TIFF_UINT8_T  uint8;
 ^
make[2]: *** [thirdparty/libtiff/CMakeFiles/tiff.dir/tif_aux.c.o] Error 1
make[1]: *** [thirdparty/libtiff/CMakeFiles/tiff.dir/all] Error 2
make: *** [all] Error 2
```
Thanks
With best regards
Martin

**Comment by boxerab** [comment]
Hi Martin,
I tested this on linux, using the image.zip file you sent above.  I was able to read and compress the image.
Aaron

**Comment by boxerab** [comment]
For some reason, I don't see your latest comments on this issue on github site, even though I received email about them. Strange. You mentioned a file snimek_001.tif; where can I download this file?

**Comment by martinhankovec** [comment]
I'm very sorry, Aaron. I have written one comment about still having problem with conversion and with compilation too, but a the same while when I have sent it I have realized the problem is on my side, so I immediately drop the comment not to mess here. Maybe it was bad idea (?)
At this time compilation and conversion of ZIP compressed TIFF works without problems, I'm testing it today; really thanks a lot...
snimek_001.tif is the same file as image.tif from image.zip available above in the first issue description. After downloading of the last version I did some mistake by compilation and have used old version of library so the same errors occured :-(
I think this issue can be successfully closed now :-) and once again - thanks for a great work!
Martin

**Comment by boxerab** [comment]
Martin,
No problem. Glad to hear it is all working now. I guess it may be better to not delete comment, but add another comment saying it is working :)  But, I did find another bug while trying to reproduce your error, so it is all good :)

Best Regards,
Aaron
