### ISSUE TITLE
Support of JPEG in opj_compress

### ISSUE THREAD

**Issue by martinhankovec** [GrokImageCompression/grok#25]
Because some documents and images coming to us from digitization workplaces are not only in TIFF but in JPEG format too (due to cameras limits), we need to convert JPEG to JPEG2000 (long preservation format) too. At present time we have to convert JPEG to TIFF first in thirdparty software and then convert them with grok from TIFF to JP2.
Can You please add support for conversion JPEGs to JPEG2000?
JPEG2000 can have lossy compression too, so there is IMHO no reason enable only lossless images on input (?).
Thanks a lot
Martin

**Comment by boxerab** [comment]
Hi Martin,

May I ask, if a file is already compressed with JPEG, what is the advantave of re-compressing as JPEG 2000?  

Thanks,
Aaron

**Comment by martinhankovec** [comment]
Hi,
we want to use one storage format for all images on input. We use lossless JPEG2000 for all images (maybe my previous issue description was not well) - both TIFF and JPEG, so for JPEG images there is no other distortion or lossy recompression.
As I have written, some cameras or other appliances used for digitization have output only in JPEG, not TIFF. Yes, of course we can convert them to TIFF and then use grok, but it would be simpler to use only one library instead of two (not creating temporary TIFF etc.).
We have similar problems on decompress too. opj_decompress supports only a few formats, it doesn't support LZW compress or other compression method in TIFF (?).
So the goal is the possibility to convert images in other common formats to/from JPEG2000 without using other library and creating temporary TIFF.
Best regards
Martin

**Comment by boxerab** [comment]
Thanks, Martin. You may open separate issues for LZW compression etc, if you like.

**Comment by boxerab** [comment]
By the way, I just added zip compression support to opj_decompress. This is now the default compression method for TIFF creation, if Grok is built with zlib support.

**Comment by boxerab** [comment]
LZW is not recommended for 16 bit images, for example.

**Comment by martinhankovec** [comment]
It sounds good, I will test it. You are right, that ZIP has better compression ratio (not only for 16 bit images).
Thanks for it.
Martin

**Comment by martinhankovec** [comment]
You have written: "... if Grok is built with zlib support"
In opj_compress ZIP support is enabled by default by:
#cmakedefine ZIP_SUPPORT
in  tif_config.h.cmake.in  file
Does it work for opj_decompress too or is any other switch to enable ZIP suuport for opj_decompress?

**Comment by martinhankovec** [comment]
There are two problems with compilation
1)
%" PRId64" or %" PRIi64"
cannot be compiled and have to be always rewritten to
%PRId64 or %PRIi64
Can You please fix it so I needn't in any new version fix it myself? (full log is bellow).

```
# make
Scanning dependencies of target openjp2
[  1%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/bio.cpp.o
[  2%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/cio.cpp.o
[  2%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/dwt.cpp.o
[  3%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/dwt_region.cpp.o
[  4%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/event.cpp.o
[  4%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/image.cpp.o
[  5%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/invert.cpp.o
[  5%] Building CXX object src/lib/openjp2/CMakeFiles/openjp2.dir/j2k.cpp.o
/home/install/grok/src/lib/openjp2/j2k.cpp: In function ‘bool opj_j2k_read_siz(opj_j2k_t*, uint8_t*, uint32_t, opj_event_mgr_t*)’:
/home/install/grok/src/lib/openjp2/j2k.cpp:2115:95: error: expected ‘)’ before ‘PRId64’
   opj_event_msg(p_manager, EVT_ERROR, "Error with SIZ marker: negative or zero image size (%" PRId64" x %" PRId64")\n", (int64_t)l_image->x1 - l_image->x0, (int64_t)l_image->y1 - l_image->y0);
                                                                                               ^
/home/install/grok/src/lib/openjp2/j2k.cpp: In function ‘void opj_j2k_dump_MH_index(opj_j2k_t*, FILE*)’:
/home/install/grok/src/lib/openjp2/j2k.cpp:8876:59: error: expected ‘)’ before ‘PRIi64’
     fprintf(out_stream, "\t Main header start position=%" PRIi64"\n"
                                                           ^
/home/install/grok/src/lib/openjp2/j2k.cpp:8884:56: error: expected ‘)’ before ‘PRIi64’
             fprintf(out_stream, "\t\t type=%#x, pos=%" PRIi64", len=%d\n",
                                                        ^
/home/install/grok/src/lib/openjp2/j2k.cpp:8911:80: error: expected ‘)’ before ‘PRIi64’
                         fprintf(out_stream, "\t\t\t tile-part[%d]: star_pos=%" PRIi64", end_header=%" PRIi64", end_pos=%" PRIi64".\n",
                                                                                ^
/home/install/grok/src/lib/openjp2/j2k.cpp:8921:68: error: expected ‘)’ before ‘PRIi64’
                         fprintf(out_stream, "\t\t type=%#x, pos=%" PRIi64", len=%d\n",
                                                                    ^
make[2]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/j2k.cpp.o] Error 1
make[1]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/all] Error 2
make: *** [all] Error 2

```

2) error in compilation
```
...
[ 44%] Linking C static library ../lib/libpng.a
[ 44%] Built target png
Scanning dependencies of target tiff
[ 44%] Building C object thirdparty/libtiff/CMakeFiles/tiff.dir/tif_aux.c.o
In file included from /home/install/grok/thirdparty/libtiff/tiffiop.h:33:0,
                 from /home/install/grok/thirdparty/libtiff/tif_aux.c:32:
/home/install/grok/thirdparty/libtiff/tif_config.h:252:0: warning: "_FILE_OFFSET_BITS" redefined [enabled by default]
 #define _FILE_OFFSET_BITS
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/fcntl.h:25:0,
                 from /home/install/grok/thirdparty/libtiff/tiffiop.h:36,
                 from /home/install/grok/thirdparty/libtiff/tif_aux.c:32:
/usr/include/features.h:300:52: error: operator '&&' has no right operand
 #if defined _FILE_OFFSET_BITS && _FILE_OFFSET_BITS == 64
                                                    ^
make[2]: *** [thirdparty/libtiff/CMakeFiles/tiff.dir/tif_aux.c.o] Error 1
make[1]: *** [thirdparty/libtiff/CMakeFiles/tiff.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by boxerab** [comment]
Hi Martin,
`#cmakedefine ZIP_SUPPORT` means that if ZIP_SUPPORT cmake variable is set, then 
`#define ZIP_SUPPORT` is added to tiff config file. But, if ZIP_SUPPORT cmake variable is not set,
then there is no #define.

So, this will work correctly. I did test this - if no zip support, then default compression is used (no compression in this case)

Aaron

**Comment by boxerab** [comment]
I fixed the second error in compilation. For the first,
what compiler version are you using?  I don't get any errors with gcc 5.4.

According to c++11 standard, there must be a trailing space before a macro in string literal.

Sounds like your compiler does not have full c++11 support.

**Comment by martinhankovec** [comment]
I have gcc 4.8.5 (CentOS 7 distribution).
I had to set too:
CMAKE_C_FLAGS			  -std=c99
because of 
for (int i = 0; i < 2; i++)
construction You have in Your code (int cannot be compiled without switch).
Could You use another syntax to make these things compatible with CentOS 7 gcc distribution version, please?

**Comment by martinhankovec** [comment]
Current version doesn't generate TIFF with ZIP compression for me (from opj_decompress).
I have downloaded, fixed some minor problems (see above) and compiled grok (no changes to defines in source code).
opj_compress reads zipped TIFF OK, but opj_decompress still generates an uncompressed TIFFs. If I after compress them with ImageMagic convert and ZIP compression, they are almost half of size.

**Comment by boxerab** [comment]
I have tested TIFF zip decompress on linux, and everything works fine. 

To get the latest master, you will have to issue these commands:

$ git fetch
$ git reset --hard origin/master

If you have local changes, you may want to issue
$ git stash

before you fetch, then

$ git stash apply 

afterwards, so you don't lose changes.

As for compile errors, I would recommend that you make a local branch, and keep changes necessary for your gcc version in this branch. It is pretty easy to do this:

$ git checkout -b centos_grok

for example

And then you can merge changes from master into your branch.

**Comment by boxerab** [comment]
Oh, forgot to mention, you need to set the compression on the command line:

`$ opj_decompress -i FOO.jp2 -o BAR.tif -OutFor TIF -c 8`

Value of 8 is the same value that tifflib uses to indicate deflate compression.
Currently, only 8 is supported, otherwise there is no compresssion

**Comment by martinhankovec** [comment]
OK, this works, thank You.

**Comment by boxerab** [comment]
Latest version of Grok can now compress JPEG images!
