### ISSUE TITLE
Image metadata are not transfered to the output image in MacOS using brew install grokj2k

### ISSUE THREAD

**Issue by giacomomarchioro** [GrokImageCompression/grok#251]
Hello Aron, 
thanks for this wonderfoul tool. 
for a project at the University I've installed grokj2k 9.2.0 usnig `brew install grokj2k` in `MacOS 10.15.7`.

`grk_compress -i original.tif -o groktest.jp2 -OutFor jp2`

Results in `groktest.jp2` having lost all the original metadata of "original.tif". Any esay fix? I looked at the issue https://github.com/GrokImageCompression/grok/issues/80 were it seems that are implemented. However `exiftool groktest.jp2` do not show any.

best regards!

**Comment by boxerab** [comment]
Hi @giacomomarchioro , thanks for posting. 
You need to add the command line flag `-V` to transfer the tags.

https://github.com/GrokImageCompression/grok/wiki/3.-grk_compress#-v--transferexiftags

**Comment by giacomomarchioro** [comment]
Thanks for the super quick reply, unfortunatly `grk_compress  -i original.tif -o groktest.jp2 -v` or `grk_compress -TransferExifTags -i original.tif -o groktest.jp2` do not transfer the metadata. I don't have any error even with the verbose mode.

While once renamed and put in the same folder I can use:

`exiftool -ext tif -tagsfromfile @ -srcfile %f.jp2 . -XMP:format= -ImageHistory='Image technical metadata values were copied (via exiftool) from a source image to this derivative JP2 copy.' -overwrite_original`

And this works, so exiftool is working properly but it seems, grok is not able to call it correctly. Am I missing something?

**Comment by boxerab** [comment]
case is important

`grk_compress -V -i original.tif -o groktest.jp2`

**Comment by boxerab** [comment]
can you share the TIFF image ?

**Comment by giacomomarchioro** [comment]
Here the  [link](https://we.tl/t-0tEdf45Ed8) Thanks

**Comment by boxerab** [comment]
@giacomomarchioro thanks for the link. Exif tag extraction has not been tested on osx with brew build,
and it looks like it silently fails. I don't have a mac to debug this on, nor the time, so my advice is to either run
a Linux VM on your system, or use exiftool directly to transfer the tags after the jp2 file is created:

`exiftool -TagsFromFile src.tif "-all:all>all:all" dest.jp2`

**Comment by giacomomarchioro** [comment]
That's totally fine for me! I can use the old method. I tried to reinstall exif tool and make sure that the perl module is available but this does not fix the issue.  I have tried to reproduced the code in https://github.com/GrokImageCompression/grok/blob/d3dfb9b839b57442541977852fd4b3c99e4d20b4/src/bin/common/exif.cpp#L44-L55

 I am not a perl user but using `perl -de1` in my mac terminal:
```
 my $info = $exifTool->ImageInfo('image.jpg');
gives:
Can't call method "ImageInfo" on an undefined value at (eval 15)[/System/Library/Perl/5.18/perl5db.pl:732] line 2.
```
defining `$exifTool = new Image::ExifTool`; as non local make it works again, but I haven't test it in depth:
```
my $srcFile = $_[0];					
my $outFile = $_[1];					
$exifTool = new Image::ExifTool;					
my $info = $exifTool->;SetNewValuesFromFile($srcFile, 'all:all');					
my $result = $exifTool->;WriteInfo($outFile);
```
I don't know if this can help for future debugging. 
Thanks for your time and efforts!

**Comment by boxerab** [comment]
ahh, I see you are running 5.18.
My version is 5.30

**Comment by boxerab** [comment]
@giacomomarchioro can you tell me what version of exiftool you are running ?
You can see the version in the first line of output from `exiftoo foo.tif`

**Comment by giacomomarchioro** [comment]
That's correct. Regarding exiftool:
```
exiftool -Ver
12.27
```

**Comment by boxerab** [comment]
@giacomomarchioro can you downgrade the exiftool version to, say 12.12 ? looks like there is an issue with latest exiftool version.

**Comment by boxerab** [comment]
for example
`brew switch exiftool 12.12`

**Comment by boxerab** [comment]
@giacomomarchioro can you run the following script on your system?

```
use Image::ExifTool qw(ImageInfo); 
use strict; 
use warnings; 
my $exifTool = new Image::ExifTool; 
my $info = $exifTool->ImageInfo('image.jpg');
```

and please post errors if it won't run.

**Comment by giacomomarchioro** [comment]
Sorry for keeping you waiting, unfortunately there is no more the switch command in brew. But I have deleted the exiftool version and installed the version 12.00 from here: https://metacpan.org/release/EXIFTOOL/Image-ExifTool-12.00

`my $info = $exifTool->ImageInfo('image.jpg'); 
`gives me:
`Can't call method "ImageInfo" on an undefined value at (eval 17)[/System/Library/Perl/5.18/perl5db.pl:732] line 2.
`
Removing `my` gives me no error.

**Comment by boxerab** [comment]
No problem. It doesn't look like it is in exiftool issue.
Can you put the script into a file like `foo.pl` and run `perl foo.pl` ?

**Comment by giacomomarchioro** [comment]
This is the ouput:
```
Global symbol "$exifTool" requires explicit package name at test2.pl line 4.
Global symbol "$exifTool" requires explicit package name at test2.pl line 5.
Execution of test2.pl aborted due to compilation errors.
```
Apparently coming from all from test2.pl

**Comment by boxerab** [comment]
Thanks. So, there's no error from the first script. 
Which means we still don't know why it's failing.
Thanks for your help, but I will have to close this again - perhaps the brew environment doesn't have
the Perl module available, or something else....
