### ISSUE TITLE
compress: export of exif tags silently fails on osx brew install

### ISSUE THREAD

**Issue by boxerab** [GrokImageCompression/grok#252]

**Comment by boxerab** [comment]
related issue: #251

**Comment by Jamaika1** [comment]
Unfortunately, I can't compile the codec correctly. EXIF under tiff doesn't work with gcc. I also don't know what modified perl5 library to use. When I added perl5-blead it turned out to be not gcc or spdlog compatible.

**Comment by Jamaika1** [comment]
Problem with decoding image. Strange pixels appear. The decoder doesn't read EXIF data.
htj2k-cgrok.exe -v -i 111.tiff -o image_21447_24bit-grok.jp2 -H 1 -M 32 -r 1
htj2k-dgrok.exe -i image_21447_24bit-grok.jp2 -o image_21447_24bit-grok.ppm -H 1

**Comment by boxerab** [comment]
`-V` command line argument only supported on Linux. For other platforms, tags can be transferred by using
`exiftool` directly:

`exiftool -TagsFromFile src.tif "-all:all>all:all" dest.jp2`
