### ISSUE TITLE
Visible pixels when decoding lossless.

### ISSUE THREAD

**Issue by Jamaika1** [GrokImageCompression/grok#253]
https://ibb.co/fDFhNjP
Visible pixels when decoding lossless. Strange because jp2 files don't have them.

**Comment by boxerab** [comment]
To address this, we need you to share to compressed original file.

**Comment by Jamaika1** [comment]
No problem
Codecs are hier
https://www.sendspace.com/file/xfuee9
htj2k-cgrok.exe -i 111.tiff -o image_21447_24bit-grok.jp2 -H 1 -M 32 -r 1
htj2k-dgrok.exe -i image_21447_24bit-grok.jp2 -o image_21447_24bit-grok.png -H 1
It's photo
https://www.sendspace.com/file/51wi8n

**Comment by boxerab** [comment]
@Jamaika1 this looks like you have built your own custom version of Grok. You will have to debug this on your own, I'm afraid.
