### ISSUE TITLE
Build from source failed!

### ISSUE THREAD

**Issue by ngoclinh93qt** [GrokImageCompression/grok#256]
Hi,

I tried to build the project from source by Cmake but got an error below:

`clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/qb/07y9p6vx7x95rf1zcyl5v2g80000gn/T/file_sinks-fa8748.cpp
clang: note: diagnostic msg: /var/folders/qb/07y9p6vx7x95rf1zcyl5v2g80000gn/T/file_sinks-fa8748.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/nik/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make[2]: *** [src/bin/jp2/CMakeFiles/grk_dump.dir/__/common/spdlog/file_sinks.cpp.o] Error 254
make[1]: *** [src/bin/jp2/CMakeFiles/grk_dump.dir/all] Error 2
make: *** [all] Error 2`

what is the error? and how to fix that?

I build on Macbook:
MacOS Big Sur
version 11.2.3

Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin.

my command:
`mkdir -p build \
cd build \
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_THIRDPARTY:BOOL=ON ../ \
make
`
Thank you!

**Comment by boxerab** [comment]
``clang: error: unable to execute command: Segmentation fault: 11`

Your compiler is crashing - please report this to Apple clang compiler people

**Comment by boxerab** [comment]
I have updated the formatting code in the library - try pull the latest version of master to see if this fixes the problem.
