### ISSUE TITLE
grok-tool installation on ubutnu 18.04

### ISSUE THREAD

**Issue by doronam** [GrokImageCompression/grok#257]
Hi, sorry if i'm writing in the wrong section, im not sure how to contact for question 

First off- this package saved my life. Im getting mildly corrupted JP2 files, which OpenJP2 doesnt seem to process well but ECW and kakadu can process them with minor defects (in some tiles of the images, Highest quality layers are corrupted but we can fix blur these with the lower quality layers), i have almost come to purchase ECW for quiet a substantial amount, before founding out about Grok which can handle these corruptions very well. So thanks!

My questions:

1. I'm trying to integrate grok into my existing docker image, yet when I install the debain packages to enable the CLI (grok-tool) within ubuntu 18.04 it fails due to package version requirements which cannot be met in ubuntu 18.04 . My installation works well on ubuntu 20.04. is there a way to install the grok-took, libgrokj2k1 and their dependencies on ubuntu 18.04? (Im trying to install from this link: https://tracker.debian.org/pkg/libgrokj2k )

2. For full integration, Is there any documentation of the source code?

**Comment by boxerab** [comment]
For Ubuntu 18, you can building from source -  you will need g++ 10 and recent version of cmake , for example 3.16. 
For full integration, you can generate doxygen docs. Also, API is quite similar to openjpeg.
You can look at projects such as gstreamer or gdal to see how to integrate
