### ISSUE TITLE
Cannot run compiled Grok on CentOS 7

### ISSUE THREAD

**Issue by martinhankovec** [GrokImageCompression/grok#263]
After compilation (gcc 11) grok compress and decompress cannot be run on CentOS 7 with error:
./grk_compress: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory

**Comment by boxerab** [comment]
Thanks for posting. Do you need to transfer Exif tags ? If not, we can try adding an option to disable exiftool support, which will remove the Perl linking.

**Comment by boxerab** [comment]
@martinhankovec can you please post the output of `ldd` command on `grk_compress`, and verify that the same version of libperl.so is present on the second machine? I suspect you have multiple versions of Perl on that one.

**Comment by martinhankovec** [comment]
Sorry, the problem is not (by Your changed title), that Grok is built on another machine. It is compiled on the same machine as I try to run: compile and run on second server works OK, compile and run on the production server returns error. 
Now: after exiftool installed and new compilation I have found the problem: executables in build directory (../grok/bin) work fine, but executables in /usr/local/bin return libperl error (?). After hand copying of executables from build directory to /usr/local/bin they work there OK now. Maybe some problem with make install or I don't know (?)
As for me, this problem seems fixed :-) Thanks for You support

**Comment by boxerab** [comment]
@martinhankovec that is odd, as `make install` should perform the same copy to `/usr/local/bin`. 
Glad this is working now.
