### ISSUE TITLE
Problem with OPENHTJ2K 

### ISSUE THREAD

**Issue by Jamaika1** [GrokImageCompression/grok#267]
Hi Grok
I see you are optimizing the ojph codec. https://github.com/GrokImageCompression/grok/commit/9c466c61a86ffc12f4890b0ff80717d4a9909015
Codecs differs in construction. How to decode photos with openjpeg which is compatible with ojph. 
dopenjpeg.exe -i image_21447_24bit-grok.j2k -o xxx4a.raw
[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[ERROR] Failed to decode.
[ERROR] Failed to decode tile 1/1
ERROR -> opj_decompress: failed to decode image!
https://github.com/uclouvain/openjpeg/pull/1374

**Comment by boxerab** [comment]
Please ask openjpeg questions on the openjpeg issue tracker.
