### ISSUE TITLE
Proposed enhancement for geospatial imagery - handling GeoTIFF tags for georeference

### ISSUE THREAD

**Issue by EmDevys** [GrokImageCompression/grok#278]
Geospatial imagery / remote sensing imagery is one of the big domain for JPEG 2000 compression, as acknowledged by JPEG committee, though of course behind digital cinema.
GeoTIFF is the well-known open standard for being able to georeference a geospatial image, in other words compute the location of a pixel on the earth for what is called orthoimagery (image in a geometry / projection similar to a map). See https://trac.osgeo.org/geotiff/ for more detail, supported by libgeotiff library.
For JPEG 2000, 2 standard or specifications are available, GMLJP2 (GML in JPEG 2000), an OGC standard see https://www.ogc.org/standards/gmljp2 or the Geotiff box in JPEG 2000 (Geotiff tags in a JPEG 2000 uuid box). Sometimes called Geo JP2.
For geospatial community, the usage of grok would imply support of GeoTIFF and at minimum one of the above mentioned option. This is recommended as an enhancement of grok (for geospatial community).
By the way, GDAL is the well-known opensource toolkit for handling GeoTIFF, GMLJP2, Geo in JPEG 2000. GDAL includes support of OpenJPEG, Kakadu, and others JPEG 2000 drivers, e.g. see https://www.ogc.org/standards/gmljp2
It would IMHO be of interest to add Grok as a JPEG 2000 driver for support of JPEG 2000 geosptial imagery.

**Comment by boxerab** [comment]
@EmDevys Thanks for your proposal. Geospatial is certainly an interesting application for the library.
I have made some attempts along these lines - for example, reading GMLJP2 from .jp2 files is supported.
I also did create a Grok driver merge request for GDAL, but I closed it due to lack of interest from GDAL community
and developers. If you would like to support a Grok driver, I could create a new MR.
Also, if you can give some more details on what is required for GeoTIFF output, we can open an enhancement issue
for this format.

**Comment by boxerab** [comment]
@EmDevys I have re-opened the gdal PR for a Grok driver. Please do add some comments
if you think this will be useful.

https://github.com/OSGeo/gdal/pull/5117

**Comment by EmDevys** [comment]
---- 
If you can give some more details on what is required for GeoTIFF output, we can open an enhancement issue
for this format.
----
Geotiff is an input format for grk_compress, the result being either GMLJP2 GeoTIFF box in JP2, or an output format for grk_decompress of geospatial image in JP2, either GMLJP2 GeoTIFF box in JP2.
As an example, Kakadu is presently handling GeoTIFF and Geotiff box, kdu_compress reading the geotiff tags and recording the geographical information tags in a GeoJP2 box within the resulting JP2 file.
Presumably, GDAL is well-suited for handling the Geo tags, either in GeoTIFF or GMLJP2, or Geo(TIFF) in JP2.
This probably makes sense for a gdal Grok driver, IMHO.

**Comment by boxerab** [comment]
@EmDevys thanks. I will look into supporting Geotiff input in the library. The Grok gdal driver pull request does support handling Geo tags.
