### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value in TCLAP::StandaloneArgs::add(TCLAP::Arg*)

### ISSUE THREAD

**Issue by shao-hua-li** [GrokImageCompression/grok#286]
### What happened?

Hi,

I found a use-of-uninitialized-value in TCLAP::StandaloneArgs::add(TCLAP::Arg*). A direct consequence of this bug is if you compile `grok` with `gcc` and `clang` separately, the results of `grk_decompress -i issue-286 -O RAW` would be different. Furthermore, the result of `gcc` compiled binary would change per run.

To reproduce:
- Compile with `gcc-11` and `clang-13` separately to obtain two binaries, `grk_decompress-gcc` and `grk_decompress-clang`
- Run `grk_decompress-gcc -i issue-286 -O RAW > out.gcc` and `grk_decompress-clang -i issue-286 -O RAW > out.clang`
- Check the checksum of `out.gcc` and `out.clang`, you would find that they are different.
- [issue-286.tar.gz](https://github.com/GrokImageCompression/grok/files/8104210/issue-286.tar.gz) (decompress it first)

If you'd like to see the report of MemorySanitizer, compile with `CC=clang CXX=clang++ CFLAGS="-g -fsanitize="memory" CXXFLAGS="-g -fsanitize=memory"` and run the above command again, you'll see the following report
```
==1816317==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4e6d31 in TCLAP::StandaloneArgs::add(TCLAP::Arg*) /grok/repo/clang13-mem-Os/src/include/tclap/CmdLine.h:62:9
    #1 0x4e6655 in TCLAP::CmdLine::_constructor() /grok/repo/clang13-mem-Os/src/include/tclap/CmdLine.h:374:19
    #2 0x4d205d in TCLAP::CmdLine::CmdLine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /grok/repo/clang13-mem-Os/src/include/tclap/CmdLine.h:338:5
    #3 0x4aff8c in grk::GrkDecompress::parseCommandLine(int, char**, grk::DecompressInitParams*) /grok/repo/clang13-mem-Os/src/bin/jp2/grk_decompress.cpp:410:18
    #4 0x4bfbaf in grk::GrkDecompress::pluginMain(int, char**, grk::DecompressInitParams*) /grok/repo/clang13-mem-Os/src/bin/jp2/grk_decompress.cpp:832:5
    #5 0x4c20ff in grk::GrkDecompress::main(int, char**) /grok/repo/clang13-mem-Os/src/bin/jp2/grk_decompress.cpp:1388:19
    #6 0x4c38bd in main /grok/repo/clang13-mem-Os/src/bin/jp2/grk_decompress.cpp:1456:16
    #7 0x7fa5b53cd0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x42b03d in _start (/shared/targets/grok/repo/clang13-mem-Os/build/bin/grk_decompress+0x42b03d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /grok/repo/clang13-mem-Os/src/include/tclap/CmdLine.h:62:9 in TCLAP::StandaloneArgs::add(TCLAP::Arg*)
```

### Version

git commit 97ea11af833564d9c05884a2284361a7b8945e87

### Operating System

Ubuntu 20.04.4 LTS, x86_64

**Comment by boxerab** [comment]
Thanks for posting this issue. Are you able to post the two different outputs, one from gcc and one from clang?
I would like to do a byte level diff on the files.

**Comment by shao-hua-li** [comment]
Here you go:

[out.gcc.tar.gz](https://github.com/GrokImageCompression/grok/files/8109241/out.gcc.tar.gz)
[out.clang.tar.gz](https://github.com/GrokImageCompression/grok/files/8109242/out.clang.tar.gz)

**Comment by boxerab** [comment]
@shao-hua-li thanks for the files. I wouldn't actually classify this as a bug - the jpeg 2000 file in question is truncated, so only one of 7 tiles is actually decompressed. The remaining tile buffers are not initialized, so what is output is compiler and system dependent. I **will** open an enhancement issue to fix this in the future, but I am going to close this one.
Also, I think the clang address sanitizer is giving a false positive for the TCLAP issue - valgrind doesn't complain
and I looked at the code and I can't see what could cause such an issue there.
