### ISSUE TITLE
[Bug]: [error] Unsupported output format TIFF

### ISSUE THREAD

**Issue by RaananHadar** [GrokImageCompression/grok#288]
### What happened?

I tried decompressing a file using the quickstart commad:
```grk_decompress -ImgDir ./in -OutFor tif -OutDir ./out```
I get the following error: `[error] Unsupported output format TIFF`
Outputting to raw seems to work fine.

### Version

9.7.0

### Operating System

ubuntu 18.04

**Comment by boxerab** [comment]
Thanks for your report. It appears that you don't have `libtiff` installed and you aren't building with third party libraries. 
Try `sudo apt install libtiff-dev` or turn on third party libraries in `cmake`.

**Comment by RaananHadar** [comment]
Thank you for the quick reply @boxerab I did what you suggested and now I am getting a different error when attempting to build grok:
```
/workspace/grok/src/bin/image_format/TIFFFormat.cpp:24:10: fatal error: tiffiop.h: No such file or directory
   24 | #include "tiffiop.h"
```
Anything specific I can do? Many thanks.

**Comment by RaananHadar** [comment]
I can provide a Dockerfile which helps in reproducing the issue if you wish.

**Comment by boxerab** [comment]
@RaananHadar thanks for persisting :) I have fixed the compile error. If you are building from the master branch, you may just pull the latest. Otherwise, let me know and we can get a build for you.

**Comment by boxerab** [comment]
version 9.7.1 has been released with the fixes. Going to close this. Thanks again for reporting.
