### ISSUE TITLE
Problem with thread

### ISSUE THREAD

**Issue by Jamaika1** [GrokImageCompression/grok#290]
### What happened?

I don't know what systems works thread codec with for new updates.
```
htj2k-cgrok_ojph.exe -v -i image_21447_24bit.raw -o image_21447_24bit-grok.j2k -H 4 -M 64 -F 1563,1558,3,8,u@1x1:1x1:1x1 -mct 1 -b 64,64 -c [128,128],[256,256] -p CPRL -r 1
```

### Version

https://github.com/GrokImageCompression/grok/commit/7e6d4af5e895f311db9695c56709b4cf8e71facb

### Operating System

Windows 10

**Comment by boxerab** [comment]
This project now uses [taskflow](https://github.com/taskflow/taskflow) for managing concurrency. You can open an issue on their issue tracker if you have questions.

@Jamaika1  this issue tracker is for library users - if you develop a fork you will have to maintain it yourself.
