### ISSUE TITLE
compress: malformed XMP metadata

### ISSUE THREAD

**Issue by bitsgalore** [GrokImageCompression/grok#295]
While doing some tests I've come around various cases where grok_compress produces JP2s with malformed embedded XMP metadata. As an example, see the TIFF image in [this ZIP file](https://github.com/GrokImageCompression/grok/files/8265020/reference-xmp.zip). I compressed this to JP2 using:
```
grk_compress -i reference-xmp.tif -o reference-grok.jp2 -I -r 2560,1280,640,320,160,80
```
The resulting JP2 fails validation in jpylyzer with;

```xml
        <uuidBox>
            <containsWellformedXML>False</containsWellformedXML>
        </uuidBox>
```
Inspection of the JP2 in a Hex editor revealed missing data both at the start and end of the XML payload (xpacket start and end tags). Compressing the same file in Kakadu produced a valid JP2 (and the embedded XMP metadata also looked fine).

The behavior seems a tad unpredictable. For some TIFFs (that I can't publicly share here for legal reasons) grk_compress initially produces a valid JP2 when run with the default compression options. Oddly,  adding the `-t` (tiles) option (e.g `-t 1024,1024`) then resulted in a JP2 with malformed XMP metadata. I don't really understand how the tiles option could even have this effect, as it seems completely unrelated to XMP embedding! If it helps I can provide an example file off-list. 

My environment:

- Linux Mint 20.1 Ulyssa (based on Ubuntu Focal Fossa 20.04). 
- Using latest (9.7.2) version of Grok
- Built with `CMAKE_BUILD_TYPE=Release` and `GROK_BUILD_THIRDPARTY:BOOL=ON` flags

**Comment by boxerab** [comment]
@bitsgalore thanks for your very detailed report. I notice that the zip you file you included has no XMP data - I checked with `exiftool`. Do you have another sample with XMP ?

**Comment by bitsgalore** [comment]
@boxerab Oops, accidentally picked the wrong image, try this one instead [reference-xmp.zip](https://github.com/GrokImageCompression/grok/files/8265020/reference-xmp.zip) (I've updated the link in my original description as well). Thanks!

**Comment by boxerab** [comment]
cc @martinhankovec

**Comment by bitsgalore** [comment]
@boxerab  brilliant, thanks for the super fast fix. Just ran a quick test and it works perfectly now!
