### ISSUE TITLE
Cmake fails on missing "thirdparty" subdirs in zip/tarball (but works fine from cloned git repo)

### ISSUE THREAD

**Issue by bitsgalore** [GrokImageCompression/grok#296]
When I try to build Grok using the release ZIP or tarball ([e.g. latest tarball here](https://github.com/GrokImageCompression/grok/archive/refs/tags/v9.7.4.tar.gz)), Cmake fails because some subdirs in the "thirdparty" directory are missing. Steps (after installing all necessary development libraries): 

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DGROK_BUILD_THIRDPARTY:BOOL=ON ..
```

This fails with:

```
CMake Error at thirdparty/CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "libz" which is not an existing directory.


-- libpng will be built
CMake Error at thirdparty/CMakeLists.txt:27 (add_subdirectory):
  add_subdirectory given source "libpng" which is not an existing directory.


-- libtiff will be built to support TIFF files.
CMake Error at thirdparty/CMakeLists.txt:54 (add_subdirectory):
  add_subdirectory given source "libtiff" which is not an existing directory.


CMake Error at thirdparty/CMakeLists.txt:86 (add_subdirectory):
  add_subdirectory given source "liblcms2" which is not an existing
  directory.
```
Running the same command from the cloned Git repo works fine without any errors whatsoever.

Since the error messages indicate the problem is related to missing subdirectories in the "thirdparty" directory, I took a closer look at this directory. In the [Github repo](https://github.com/GrokImageCompression/grok/tree/master/thirdparty) it contains subdirectories for liblcms2, libpng, libtiff and libz. However, these subdirectories are all absent in the release distribution tarball + ZIP, and this causes the build configuration to fail (I double checked this by copying those dirs over from the Git repo, after which the problem disappears).

Not entirely sure if this is a shortcoming of the zips/tarballs, or perhaps I'm simply overlooking some build option here (I don't really know anything much about build configurations for C++ projects, and I'm just following the docs).

Using Linux Mint 20.1 Ulyssa, based on Ubuntu Focal Fossa 20.04.

**Comment by boxerab** [comment]
@bitsgalore thanks very much for reporting this issue. The problem was that `.gitattributes` was filtering third party folders out for archive generation via git. Fixed now.

**Comment by bitsgalore** [comment]
@boxerab already suspected something like that, great to see this fixed.
