### ISSUE TITLE
Question: How to compress images larger than RAM?

### ISSUE THREAD

**Issue by emmenlau** [GrokImageCompression/grok#303]
Is it possible to create JPEG2000 images larger than the computer RAM? Or to be more precise, is it possible to make partial writes to a huge JPEG2000, while limiting the required RAM?

A practical use case is aerial images where the final image may be hundreds of gigabytes in size, but it is composed of many much smaller images that are acquired incrementally. Does JPG2000 support such incremental writes by any means, and if so, does Grok support it?

**Comment by boxerab** [comment]
Thanks for your question. JPEG 2000 supports tiling of images, where each tile is a self contained compressed piece of the complete image. This would allow writing an image larger than available RAM. Grok supports tiled image compression, but I'm not sure in practice what issues would arise for writing images larger than RAM. If you can put together some more details this can be tested. 

It's also possible to do incremental writes for a large single-tiled image, but this functionality is not currently supported.

**Comment by emmenlau** [comment]
Oh nice, both options would be very interesting!

About the tiling of images:
 - Does the file still support the pyramid of lower-resolution images? That would be very helpful for our use case.
 - I assume each image is compressed independently, is that correct? So for the lossless case, a tiled image would probably be a bit bigger than a non-tiled image, correct?

About the incremental writes, how does that behave with respect to compression ratio, and memory usage?

**Comment by boxerab** [comment]
Yes, tiling still allows lower resolution replicas to be generated. Can you share what your use case is ?
Tiling adds some overhead for the tile headers, also if the image is that large, a TLM marker is highly recommended for faster random access to arbitrary tiles. The only disadvantage of tiling is that for low bit rate lossy, there can be artifacts at the tile boundaries.

Incremental write can be achieved with a fixed memory buffer that would fit into any modern computer's RAM. The advantage of single tile is that there are no artifacts at tile boundaries; disadvantage is that random access is going to be slower than with tiles for certain image progressions.  Also, if the image is large, then it's highly advantageous to have PLT markers for random access.

**Comment by boxerab** [comment]
Hopefully that answers your questions - please re-open if more questions arise.
