### ISSUE TITLE
[Bug]: Unable to create lossy HT codestreams

### ISSUE THREAD

**Issue by ruven** [GrokImageCompression/grok#312]
### What happened?

Using grk_compress works fine when creating a lossless HT codestream. However, only the header is emitted when requesting lossy encoding via the -r parameter.

The following works correctly: `grk_compress -i in.tif -o out.j2c -M 64 -r 1`

However, only the header seems to be output with: `grk_compress -i in.tif -o out.j2c -M 64 -r 8`

### Version

Latest master branch

### Operating System

Ubuntu 22.04

**Comment by boxerab** [comment]
Thanks for reporting. The issue here is that Part 15 of the standard doesn't include a rate control algorithm, so one can't set r != 1 for HTJ2K, at least in this library. Rate control algorithms do exist, but it's much more difficult to implement. The solution here is to simply prevent the user from setting the `-r` argument, or `-q` for that matter, if HTJ2K is enabled.

**Comment by ruven** [comment]
OK, I see. Thanks for your help. You should maybe add a note on this in the manual.

**Comment by kubouch** [comment]
> > @boxerab Just to clarify: Does this mean that the HT mode can only produce lossless bitstreams?
> 
> No, lossy is also supported, with `-I` command line arg. What HT doesn't support is a specified bit rate for the output. So, it's not possible to specify a compression ratio or quality level.

I see. So you can turn on the irreversible transform with the `-I` flag but there is no other parameter to increase the compression ratio in the HT mode?

I know that rate control is not implemented. I'm thinking a parameter like JPEG's Q number that increases the quantization but you don't know exactly how much in advance. Is there something similar for the HT mode?

**Comment by boxerab** [comment]
Yes, there is a Q factor for HTJ2K, not implemented at the moment. If you're interested in this feature, feel free to open an issue on the tracker.
