### ISSUE TITLE
[Bug]: Problem with decompressing files.

### ISSUE THREAD

**Issue by Jamaika1** [GrokImageCompression/grok#315]
### What happened?

htj2k-dgrok_ojph.exe -i image_21447_24bit-grokjph.j2k -o image_21447_24bit-grokjph.ppm -H 1

Nothing happens

### Version

9.7.7

### Operating System

Windows10

**Comment by boxerab** [comment]
Once again, please don't open issues for your fork on this tracker. You will have to debug it yourself.
