### ISSUE TITLE
How to correctly decompress HTJ2K?

### ISSUE THREAD

**Issue by Jamaika1** [GrokImageCompression/grok#323]
I used c++20 and c2x for additions. I added new OpenJPH 0.9.0 codecs.
How to decompress files by grok? With OpenJPH I make it.
I am asking only for new OpenJPH codecs because I can create them correctly.

htj2k-cgrok_ojph.exe -v -i image_21447_24bit.png -o image_21447_24bit-grokjph.j2k -H 1 -M 64 -r 1
htj2k-dgrok_ojph.exe -i image_21447_24bit-grokjph.j2k -o image_21447_24bit-grokjph.ppm -H 1

https://www.sendspace.com/file/gjom2i

**Comment by boxerab** [comment]
Once again, this issue tracker is only intended for users of **this** library; if you have a fork, you must figure things out yourself.

**Comment by Jamaika1** [comment]
I must nothing. Thanks for the answer.
