### ISSUE TITLE
[Bug]: grk_compress and grk_decompress do not work on Win11

### ISSUE THREAD

**Issue by maffe69** [GrokImageCompression/grok#324]
### Contact Details

marco.maffezzoli@live.com

### What happened?

There are two related issues:
1) If launched directly from the command line, both grk_compress and grk_decompress do not produce any output, or error message of any kind... they just do nothing. You can't even get them to show the help with -h ... it doesn't work.
2) If launched from a batch file, several error messages arise, and report the following libraries missing:

msvcp140d.dll
vcruntime140d.dll
vcruntime140_1d.dll
ucrtbased.dll

### Version

9.7.8

### Operating System

windows 11

**Comment by boxerab** [comment]
@maffe69 I'm sorry to hear you are having trouble with the build.
Unfortunately, a Windows 11 binary is not currently produced by our build servers, as they run on Windows Server 2022
which is based on Windows 10. 

If you would like to build from source, there are instructions in [here](https://github.com/GrokImageCompression/grok/blob/master/INSTALL.md)

You will need to download and install [Visual Studio](https://visualstudio.microsoft.com/vs/community/)
and install Desktop C++ environment.

We can walk you through it if you're interested - it should take about an hour tops.

**Comment by maffe69** [comment]
Thanks for your reply. No worries, version 9.7.1 works perfectly under windows 11, and I will continue use that one. Unfortunately, all the more recent versions (9.7.5 onwards) present the bug I was describing above. Compiling from source is way above my level of incompetence, I'm afraid.

**Comment by boxerab** [comment]
@maffe69 I've made one change that might get the build working on windows 11. Would you mind downloading the binary from the 9.7.8 release and trying again ?

**Comment by maffe69** [comment]
Great, thanks! Now it works perfectly, as far as I can see. Well, I'm really impressed by how quickly this got solved. Kudos!

**Comment by boxerab** [comment]
Thanks! Glad to hear it is working now, and thanks a lot for reporting the issue.
