### ISSUE TITLE
[Bug]: Crash when decoding J2K codestream originating from DICOM files (medical images)

### ISSUE THREAD

**Issue by pfillard** [GrokImageCompression/grok#332]
### Contact Details

pierre.fillard@gmail.com

### What happened?

I experience a crash when decoding a J2K codestream taken from a medical image.

The crash can be reproduced with example `core_decompress_from_file` and passing the input file available at this [link](https://drive.google.com/file/d/1SrC5jk4y88d4hJQodHPyF3SpJR72KvPA/view?usp=sharing). See relevant log below (grok compiled with debug info).

The very same file gets decoded properly using OpenJPEG:

```
> opj_decompress -i ../pylibjpeg-grok/blob.jp2 -o test.pgm

===========================================
The extension of this file is incorrect.
FOUND .jp2. SHOULD BE .j2k or .jpc or .j2c or .jhc
===========================================

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[INFO] Generated Outfile test.pgm
decode time: 464 ms

```

It's likely that this stream does not strictly follow the standard. For instance, there is a trailing \x00 after the EOC marker - medical image providers have the tendency to do things as they like. Yet, this is a pretty standard file commonly encountered. The fact that OpenJPEG manages to decompress it indicates that this type of file, while being wrong to some extent, shall be supported. Also, the fact that Grok crashes with an assertion seems to indicate that this case is not well handled.

Thanks for your assistance on this matter.

### Version

- master as to date
- v10.0.4
- Probably older versions too

### Operating System

Ubuntu 20.04
clang-12

### Relevant log output

```shell
> core_decompress_from_file blob.jp2
Decompressing file blob.jp2

Image Info
Width: 1996
Height: 2457
Number of components: 1
Precision of component 0 : 16
Number of tiles: 1
Packet data is truncated or packet header is corrupt :
at component=00 resolution=03 precinct=000 layer=01
core_decompress_from_file:grok/src/lib/core/t2/BitIO.cpp:29: grk::BitIO::BitIO(uint8_t *, uint64_t, bool): Assertion `isCompressor || bp' failed.
Aborted (core dumped)
```

**Comment by boxerab** [comment]
Thanks for reporting this issue , and uncovering this bug ! Fixed now.

**Comment by pfillard** [comment]
I confirm that your changes does fix the issue.

Thanks A LOT for your reactivity and your excellent work. Grok is amazing!
