### ISSUE TITLE
apply_icc issues

### ISSUE THREAD

**Issue by dvhassel** [GrokImageCompression/grok#333]
### What happened?

I'm trying to convert uncompressed TIF files while preserving the EXIF metadata and color profiles.

(partial) EXIF from test.tif:

```
Unique Camera Model             : CamQuartzHD1.
Localized Camera Model          : CamQuartzHD1.
(...)
Profile Creator                 : Adobe Systems Inc.
Profile ID                      : 0
Profile Copyright               : (c) 1998 Adobe Systems Inc.
Profile Description             : Adobe RGB (1998)

```
compressing using

`grk_compress -i test.tif -o test.jp2 -v -V -f`

results in an sRGB file:

```
ExifTool Version Number         : 12.55
File Name                       : test.jp2
Directory                       : .
File Size                       : 28 MB
File Modification Date/Time     : 2023:02:06 09:02:29+01:00
File Access Date/Time           : 2023:02:06 09:02:29+01:00
File Creation Date/Time         : 2023:02:06 09:02:27+01:00
File Permissions                : -rw-rw-rw-
File Type                       : JP2
File Type Extension             : jp2
MIME Type                       : image/jp2
Major Brand                     : JPEG 2000 Image (.JP2)
Minor Version                   : 0.0.0
Compatible Brands               : jp2
Image Height                    : 7010
Image Width                     : 5357
Number Of Components            : 3
Bits Per Component              : 8 Bits, Unsigned
Compression                     : JPEG 2000
Color Spec Method               : Enumerated
Color Spec Precedence           : 0
Color Spec Approximation        : Not Specified
Color Space                     : sRGB
Capture Y Resolution            : 23622
Capture X Resolution            : 23622
Capture Y Resolution Unit       : m
Capture X Resolution Unit       : m
Image Size                      : 5357x7010
Megapixels                      : 37.6
```

for a second test2.tif file with exif

```
ExifTool Version Number         : 12.55
File Name                       : test2.tif
Directory                       : .
File Size                       : 4.6 MB
File Modification Date/Time     : 2020:02:20 17:15:48+01:00
File Access Date/Time           : 2023:02:06 09:04:49+01:00
File Creation Date/Time         : 2023:02:06 08:49:35+01:00
File Permissions                : -rw-rw-rw-
File Type                       : TIFF
File Type Extension             : tif
MIME Type                       : image/tiff
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Full-resolution image
Image Width                     : 1498
Image Height                    : 1031
Bits Per Sample                 : 8 8 8
Compression                     : Uncompressed
Photometric Interpretation      : RGB
Fill Order                      : Normal
Strip Offsets                   : 8
Samples Per Pixel               : 3
Rows Per Strip                  : 1031
Strip Byte Counts               : 4633314
X Resolution                    : 300
Y Resolution                    : 300
Planar Configuration            : Chunky
Resolution Unit                 : inches
Software                        : LibTiff Version 4.0.3
Image Size                      : 1498x1031
Megapixels                      : 1.5
```

grk_compress crashes when using -f

Both TIF files are valid according to JHOVE

### Version

tested with 10.0.2 and 10.0.4

### Operating System

win10, exiftool 12.55

**Comment by boxerab** [comment]
Thanks for reporting. Would you mind sharing the test files ? Also,  can you please show output of exiftool
for result of the first test TIFF ? I'm not entirely sure that -V argument works on windows.

**Comment by dvhassel** [comment]
sure, here's a WeTransfer link with both files: https://we.tl/t-NwrgOPXzei

```
grk_compress.exe -i test.tif -o test.jp2 -v -V -f
[2023-02-06 16:38:55.991] [warning] libtiff: Unknown field with tag 36867 (0x9003) encountered
[2023-02-06 16:38:55.992] [warning] libtiff: Unknown field with tag 36868 (0x9004) encountered
[2023-02-06 16:38:58.802] [info] compress time: 2811.4336999999996 ms
```

the above with test2.tif crashes before any output happens

**Comment by boxerab** [comment]
Thanks. Are you sure you want the `-f` argument ? This forces application of the ICC profile to the image, and there will be no profile stored in the jp2. If you then transfer tags with -V, then there will be a profile stored, but it will now be incorrect.

**Comment by dvhassel** [comment]
All our images are RGB, and have either no profile attached or Adobe 1998.  I'd like to have our JP2 versions have the same color rendering.  What do you suggest in this case?

**Comment by boxerab** [comment]
In that case, `-f` will work for you, but you will need a way of not transferring the ICC profile tags, since ICC has already been applied.  By the way, which version of Perl do you have installed ?

**Comment by boxerab** [comment]
I've fixed the crash, by the way. You can get the latest build here :

https://github.com/GrokImageCompression/grok/actions/runs/4105644982

or wait for the next point release, which will be out in a few days.

**Comment by boxerab** [comment]
So, it turns out that you don't have to worry about ICC profiles as `-V` will not transfer them.
However, it does look like you don't exiftool Perl modules installed, so `-V` is not doing anything.
I will update the INSTALL document to show what needs to be done.

**Comment by boxerab** [comment]
Latest release (with fix)

https://github.com/GrokImageCompression/grok/releases/tag/v10.0.5

**Comment by boxerab** [comment]
@dvhassel unfortunately, you won't be able to transfer ExIF tags from inside Grok on Windows, but you can use exiftool directly to do it after compressing the files. See INSTALL.md for details.
