### ISSUE TITLE
[Bug]: checksum of release 10.0.5 changed

### ISSUE THREAD

**Issue by SMillerDev** [GrokImageCompression/grok#336]
### What happened?

When Homebrew updated to 10.0.5 on 07-02-2023 at 14:54:55+0100, the checksum for the release was `963a067aaa986e13d8000af82a47d25df974050a0a3c1c8cfb78ebc37797daf4` but now it is `963a067aaa986e13d8000af82a47d25df974050a0a3c1c8cfb78ebc37797daf4` was the release retagged or was the repo somehow compromised?

We're tracking this change in: https://github.com/Homebrew/homebrew-core/pull/124311

### Version

10.0.5

### Operating System

macOS 13.2

**Comment by boxerab** [comment]
Thanks for reporting, I did retag the release to add a fix. It's probably not a good idea to do this :)
I will just make a new release in future.

**Comment by SMillerDev** [comment]
Thanks for the confirmation, yeah the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.
