### ISSUE TITLE
[Bug]: `grk_decompress -help` prints help for compress not decompress

### ISSUE THREAD

**Issue by overlookmotel** [GrokImageCompression/grok#343]
### What happened?

`grk_decompress -help` prints the same usage info as `grk_compress -help` i.e. it doesn't seem relevant to `grk_decompress`.

Please don't take brevity of above description as rudeness. There just isn't that much to say! Very excited to come across this project.

### Version

10.0.7

### Operating System

Mac OS 12.6.2 (M1), installed via Homebrew.

**Comment by boxerab** [comment]
Thanks for reporting! Fixed now in master.
