### ISSUE TITLE
Feature: Decompress image sequence to PNM over stdout

### ISSUE THREAD

**Issue by overlookmotel** [GrokImageCompression/grok#344]
Is it possible to decompress a sequence of images to PNM over stdout with the output containing a stream of images? Purpose is for piping to ImageMagick or FFMPEG for further processing.

I tried:

```sh
grk_decompress -y input -out_fmt PNM > output.pnm
```

but this wrote each frame as an individual file to the "input" directory and `output.pnm` contained error messages "[error] No JPEG code stream detected" (presumably because it tried to read some of the `.pnm` files it wrote to the directory back in again as J2K files).

**Comment by overlookmotel** [comment]
PS I'm not set on PNM as the output format. Just chose that as it's a "lingua franca" format which supports multiple images in one file/stream.

**Comment by boxerab** [comment]
STDOUT is only supported for single file decompress . If you want to do a batch, you can just write a short script that
decompresses to /tmp directory (which is in RAM) and then run `gm convert` on the resulting file. That will also allow you to use any supported decode format, such as TIFF.
