### ISSUE TITLE
HTJ2K features written to JP2 instead of JPH?

### ISSUE THREAD

**Issue by bitsgalore** [GrokImageCompression/grok#346]
Seeing that Grok now supports HTJ2K, I did a few tests with v 10.0.8 to to see if I could use it to generate some JPH test images for the [Jpylyzer test files repo](https://github.com/openpreserve/jpylyzer-test-files) (I'd like to add HTJ2K support to an upcoming version of Jpylyzer). 

First I tried this (assuming that Grok would recognise/support the JPH file extension as per the [standard](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.814-201906-I!!PDF-E&type=items)):

```
grk_compress -i aware.tif -o aware-ht.jph -M 64
```

But this throws:

```
[2023-09-11 15:44:16.364] [error] Unknown output format image aware-ht.jph [only *.j2k, *.j2c or *.jp2] 
```

This *does* work:

```
grk_compress -i aware.tif -o aware-ht.jp2 -M 64
```

But the resulting file is in JP2 format. I double-checked this with Jpylyzer, which also revealed the file doesn't actually conform to JP2:

```xml
    <isValid format="jp2">False</isValid>
    <tests>
        <contiguousCodestreamBox>
            <siz>
                <rsizIsValid>False</rsizIsValid>
            </siz>
        </contiguousCodestreamBox>
    </tests>
```
A quick look at the [HTJ2K standard](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.814-201906-I!!PDF-E&type=items) shows why:

> **A.2 SIZ marker segment**
> Bit 14 of Rsiz shall be equal to 1.

So this is a constraint that is specific to JPH and the HTJ2K codestream spec. 

Am I right in assuming here that Grok simply writes the HTJ2K-specific features directly to JP2, without using the designated JPH format? If yes: is there any particular reason for this? Because mixing up features from 2 different standards/formats like this can lead to all sorts of interoperability problems. E.g. as a quick test I tried to open the file in  GIMP, which (predictably) fails at this.

**Comment by boxerab** [comment]
@bitsgalore thanks for raising this issue. You are right - the library is currently lacking full support for jph and jpc formats.
I will put this on the todo list, but it may be some time before I have bandwidth to take a look.

**Comment by bitsgalore** [comment]
@boxerab Thanks for confirming this!

**Comment by boxerab** [comment]
@bitsgalore this should be fixed now - if `.jpc` or `.jph` tag is used when encoding, then `-M 64` will automatically be added to the encoding parameters, creating an HTJ2K file. Otherwise, `-M 64` is not allowed as an encoder parameters, so that user cannot create a jp2 file with HTJ2K features.
