### ISSUE TITLE
[Bug]: -in_dir argument not working

### ISSUE THREAD

**Issue by kidon0011** [GrokImageCompression/grok#347]
### Contact Details

shinb37kidon@gmail.com

### What happened?

Attempting to use the input directory argument is no longer working. My usual process looks like: $grk_compress -ImgDir . -OutFor jp2 -OutDir [Output directory path]

I noticed the arguments changed and ImgDir wasn't working anymore. I tried the new "-in_dir" and "out_dir" a couple of weeks ago and that worked but now after updating to the latest version, using -in_dir no longer works. I can only use arguments for single files -i and -o. I need to be able to run this against an entire directory.

### Version

v10.0.8

### Operating System

Intel based macOS Venture 13.5.2

### Relevant log output

```shell
error: Couldn't find match for argument for arg Argument: -in_dir
```

**Comment by myshkinp** [comment]
@kidon0011 thanks for reporting - the correct flag is `batch_src`. I've corrected the documentation and pushed that to master.

**Comment by boxerab** [comment]
@kidon0011 the correct argument is `batch_src`. Now fixed in master.
