### ISSUE TITLE
Using grok from a libray

### ISSUE THREAD

**Issue by FrancescAlted** [GrokImageCompression/grok#350]
Hi.  We are trying to create a [plugin of the grok library for Blosc2](https://github.com/Blosc/blosc2_grok).  We are able to do compression, but for decompression the code gets stuck waiting for something, although we cannot figure out what it is.  You can reproduce our issue with:

```bash
$ git clone https://github.com/Blosc/blosc2_grok.git
$ cd blosc2_grok
$ mkdir build
$ cd build
$ cmake ..
$ make -j
$ src/grok/bin/test_grok
Compression succeeded: 3243 bytes used.
Compress OK:	cratio: 185.339 x
Decompressing buffer

Image Info
Width: 640
Height: 480
Number of components: 1
Precision of component 0 : 16
Number of tiles: 1
^C⏎
```

We have tracked down that test_grok hangs at the [grk_decompress()](https://github.com/Blosc/blosc2_grok/blob/main/src/blosc2_grok.cpp#L205) function, and it makes no progress after that.

We are trying to follow the example at: https://github.com/GrokImageCompression/grok/tree/master/examples/core.  Are we missing something?  Is grok meant to be used from libraries? Thanks in advance.

**Comment by FrancescAlted** [comment]
Oh, forgot to mention that you need the [C-Blosc2 library](https://github.com/Blosc/c-blosc2) installed to compile the plugin above.  Alternatively, the C-Blosc2 library can also be easily installed using the binary wheel of the Python-Blosc2 wrapper: `pip install blosc2`

**Comment by FrancescAlted** [comment]
Ok, so my colleague discovered the issue: we have been deinitializing grok per every call to compress/decompress, which was definitely wrong.  Our fix is here: https://github.com/Blosc/blosc2_grok/commit/7bc628b5b13bef85a9a0e47c6bd86b44c4873744

With that, the output is now:

```
$ src/grok/bin/test_grok
Compression succeeded: 3243 bytes used.
Compress OK:	cratio: 185.339 x
Decompressing buffer

Image Info
Width: 640
Height: 480
Number of components: 1
Precision of component 0 : 16
Number of tiles: 1
Component 0 : dimensions (640,480) at precision 16
Decompress OK
Error: decompressed data differs from original!
  position: 1, value in original image: 2, value in output: 0
Process finished with exit code 255

```

So now, the decompression process finishes correctly (no need to press ^C). Our image test still does not pass (i.e. it cannot not make our synthetic 16-bit gray image do an identical roundtrip), but I am not sure if it is because grok uses lossy compression by default or, most probably, there is still a bug in our buffer copies (converting from 16-bit input images to grok's internal 32-bit representation and back).  Anyway, closing.

**Comment by boxerab** [comment]
Glad you figured it out. I see your project is licensed under BSD - unfortunately this license is not compatible with Grok AGPL license, in the sense that if Grok is added as plugin, then the rest of the library must be distributed under the AGPL license. I just wanted to make sure you are aware of this issue.

**Comment by FrancescAlted** [comment]
Well, the plugin itself (https://github.com/Blosc/blosc2_grok) is AGPL already.  C-Blosc2 can load completely on-demand the plugin by using the dlopen / LoadLibrary mechanism, but its is completely agnostic about the grok library itself (and of course, it is not distributing any part of grok).  So I think C-Blosc2 should not be considered a derivative work, and hence not in need to change the current license (at least, this is my perception).
