### ISSUE TITLE
Trying to build for devKitPro Nintendo Switch gives an error on the "tests" folder's CMakeLists.txt (file)

### ISSUE THREAD

**Issue by MrBolt2005** [GrokImageCompression/grok#354]
$ cmake -S . -B build-switch -DCMAKE_BUILD_TYPE=RelWithDebInfo --toolchain=$DEVKITPRO/cmake/Switch.cmake
-- Architecture: aarch64
CMake Deprecation Warning at cmake/ucm.cmake:13 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:103 (include)

-- zlib will be built.
-- Using CMake version 3.28.1
-- ZLIB_HEADER_VERSION: 1.2.13
-- ZLIBNG_HEADER_VERSION: 2.1.0.devel
-- Arch not recognized, falling back to cmake arch: 'aarch64'
-- Basearch of 'aarch64' has been detected as: 'arm'
-- Using CMake toolchain: /opt/devkitpro/cmake/Switch.cmake
-- Architecture-specific source files: arch/arm/arm_features.c;arch/arm/crc32_acle.c;arch/arm/insert_string_acle.c;arch/arm/adler32_neon.c;arch/arm/chunkset_neon.c;arch/arm/compare256_neon.c;arch/arm/slide_hash_neon.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: RelWithDebInfo (selected)
 * ACLE_CRC, Support ACLE optimized CRC hash generation, using "-march=armv8-a+crc"
 * NEON_ADLER32, Support NEON instructions in adler32, using "-march=armv8-a+simd"
 * NEON_SLIDEHASH, Support NEON instructions in slide_hash, using "-march=armv8-a+simd"
 * WITH_GZFILEOP, Compile with support for gzFile related functions
 * ZLIB_COMPAT, Compile with zlib compatible API
 * ZLIBNG_ENABLE_TESTS, Test zlib-ng specific API
 * WITH_SANITIZER, Enable sanitizer support
 * WITH_GTEST, Build gtest_zlib
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_ACLE, Build with ACLE
 * WITH_NEON, Build with NEON intrinsics

-- The following features have been disabled:

 * ZLIB_SYMBOL_PREFIX, Publicly exported symbols DO NOT have a custom prefix
 * ZLIB_ENABLE_TESTS, Build test binaries
 * WITH_FUZZERS, Build test/fuzz
 * WITH_BENCHMARKS, Build test/benchmarks
 * WITH_BENCHMARK_APPS, Build application benchmarks
 * WITH_NATIVE_INSTRUCTIONS, Instruct the compiler to use the full instruction set on this host (gcc/clang -march=native)
 * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
 * WITH_CODE_COVERAGE, Enable code coverage reporting
 * WITH_INFLATE_STRICT, Build with strict inflate distance checking
 * WITH_INFLATE_ALLOW_INVALID_DIST, Build with zero fill for inflate invalid distances
 * INSTALL_UTILS, Copy minigzip and minideflate during install

-- We will build libjpeg-turbo library
-- libpng will be built
CMake Deprecation Warning at thirdparty/libpng/CMakeLists.txt:5 (cmake_policy):
  The OLD behavior for policy CMP0115 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- libtiff will be built to support TIFF files.
-- Building tiff version 4.5.1
-- libtiff library version 6.0.1
-- libtiff build date: 20231229
-- Could NOT find Deflate (missing: Deflate_LIBRARY Deflate_INCLUDE_DIR)
-- Could NOT find JBIG (missing: JBIG_LIBRARY JBIG_INCLUDE_DIR)
-- Could NOT find LERC (missing: LERC_LIBRARY LERC_INCLUDE_DIR)
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
CMake Deprecation Warning at thirdparty/libtiff/doc/CMakeLists.txt:27 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
-- Looking for sphinx-build - not found
CMake Warning at thirdparty/libtiff/doc/CMakeLists.txt:145 (message):
  Manual pages and HTML manual will not be generated or installed

--
-- Libtiff is now configured for NintendoSwitch-1
--
--   Installation directory:             /opt/devkitpro/portlibs/switch
--   Documentation directory:            share/doc/GROK
--   C compiler:                         /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe
--   C++ compiler:                       /opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++.exe
--   Build shared libraries:             OFF
--   Build tools:                        ON
--   Build tests:                        ON
--   Build contrib:                      ON
--   Build docs:                         ON
--   Build deprecated features:          OFF
--   Enable linker symbol versioning:    TRUE
--   Support Microsoft Document Imaging: ON
--   Use win32 IO:                       OFF
--
--  Support for internal codecs:
--   CCITT Group 3 & 4 algorithms:       ON
--   Macintosh PackBits algorithm:       ON
--   LZW algorithm:                      ON
--   ThunderScan 4-bit RLE algorithm:    ON
--   NeXT 2-bit RLE algorithm:           ON
--   LogLuv high dynamic range encoding: ON
--
--  Support for external codecs:
--   ZLIB support:                       Requested:ON Availability:TRUE Support:TRUE
--   libdeflate support:                 Requested:OFF Availability:FALSE Support:FALSE
--   Pixar log-format algorithm:         Requested:ON Availability:TRUE Support:TRUE
--   JPEG support:                       Requested:ON Availability:TRUE Support:TRUE
--   Old JPEG support:                   Requested:ON Availability:TRUE Support:TRUE
--   JPEG 8/12 bit dual mode:            Requested:OFF Availability:FALSE Support:FALSE
--   ISO JBIG support:                   Requested:OFF Availability:FALSE Support:FALSE
--   LERC support:                       Requested:OFF Availability:FALSE Support:FALSE
--   LZMA2 support:                      Requested:ON Availability:TRUE Support:TRUE
--   ZSTD support:                       Requested:ON Availability:TRUE Support:TRUE
--   WEBP support:                       Requested:ON Availability:TRUE Support:TRUE
--
--   C++ support:                        ON (requested) TRUE (availability)
--
--   OpenGL support:                     Requested:OFF Availability:FALSE Support:FALSE
--
-- We will build LCMS2 library
CMake Deprecation Warning at src/lib/core/highway/CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0111 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Perl libraries found
-- ExifTool Perl module not found
CMake Error at CMakeLists.txt:221 (add_subdirectory):
  The source directory

    /home/joao2/Downloads/grok-11.0.0/tests

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by boxerab** [comment]
If you downloaded the tarball, you need to disable testing by adding `-DBUILD_TESTING=OFF` to your cmake command

**Comment by MrBolt2005** [comment]
Now it does make the makefile, but it fails with the following output:

```
$ make
[  0%] Creating directories for 'libjpeg-turbo'
[  0%] Performing download step (git clone) for 'libjpeg-turbo'
Cloning into 'libjpeg-turbo'...
HEAD is now at 8ecba364 ChangeLog.md: Document d743a2c1
[  1%] Performing update step for 'libjpeg-turbo'
[  1%] No patch step for 'libjpeg-turbo'
[  1%] Performing configure step for 'libjpeg-turbo'
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe
-- Check for working C compiler: /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    Run Build Command(s): /usr/bin/cmake.exe -E env VERBOSE=1 /usr/bin/make.exe -f Makefile cmTC_a5ba6/fast
    make[3]: Entrando no diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    /usr/bin/make  -f CMakeFiles/cmTC_a5ba6.dir/build.make CMakeFiles/cmTC_a5ba6.dir/build
    make[4]: Entrando no diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    Building C object CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o
    /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe   -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -O2 -ffunction-sections -fdata-sections  -o CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o -c /home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v/testCCompiler.c
    Linking C executable cmTC_a5ba6.exe
    /usr/bin/cmake.exe -E cmake_link_script CMakeFiles/cmTC_a5ba6.dir/link.txt --verbose=1
    /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -O2 -ffunction-sections -fdata-sections  -Wl,--enable-auto-import -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -L/opt/devkitpro/portlibs/switch/lib -L/opt/devkitpro/libnx/lib  CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o -o cmTC_a5ba6.exe -Wl,--out-implib,libcmTC_a5ba6.dll.a -Wl,--major-image-version,0,--minor-image-version,0
    D:/msys64/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld.exe: unrecognized option '--enable-auto-import'
    D:/msys64/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld.exe: use the --help option for usage information
    collect2.exe: error: ld returned 1 exit status
    make[4]: *** [CMakeFiles/cmTC_a5ba6.dir/build.make:99: cmTC_a5ba6.exe] Error 1
    make[4]: Saindo do diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    make[3]: *** [Makefile:127: cmTC_a5ba6/fast] Error 2
    make[3]: Saindo do diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'






  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)


-- Configuring incomplete, errors occurred!
make[2]: *** [thirdparty/CMakeFiles/libjpeg-turbo.dir/build.make:92: thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-stamp/libjpeg-turbo-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:514: thirdparty/CMakeFiles/libjpeg-turbo.dir/all] Error 2
make: *** [Makefile:156: all] Error 2```
