### ISSUE TITLE
Trying to build for devKitPro Nintendo Switch gives an error when going to build the libjpeg-turbo component

### ISSUE THREAD

**Issue by MrBolt2005** [GrokImageCompression/grok#355]
`$ make
[  0%] Creating directories for 'libjpeg-turbo'
[  0%] Performing download step (git clone) for 'libjpeg-turbo'
Cloning into 'libjpeg-turbo'...
HEAD is now at 8ecba364 ChangeLog.md: Document d743a2c1
[  1%] Performing update step for 'libjpeg-turbo'
[  1%] No patch step for 'libjpeg-turbo'
[  1%] Performing configure step for 'libjpeg-turbo'
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe
-- Check for working C compiler: /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    Run Build Command(s): /usr/bin/cmake.exe -E env VERBOSE=1 /usr/bin/make.exe -f Makefile cmTC_a5ba6/fast
    make[3]: Entrando no diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    /usr/bin/make  -f CMakeFiles/cmTC_a5ba6.dir/build.make CMakeFiles/cmTC_a5ba6.dir/build
    make[4]: Entrando no diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    Building C object CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o
    /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe   -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -O2 -ffunction-sections -fdata-sections  -o CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o -c /home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v/testCCompiler.c
    Linking C executable cmTC_a5ba6.exe
    /usr/bin/cmake.exe -E cmake_link_script CMakeFiles/cmTC_a5ba6.dir/link.txt --verbose=1
    /opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc.exe -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -O2 -ffunction-sections -fdata-sections  -Wl,--enable-auto-import -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -L/opt/devkitpro/portlibs/switch/lib -L/opt/devkitpro/libnx/lib  CMakeFiles/cmTC_a5ba6.dir/testCCompiler.c.o -o cmTC_a5ba6.exe -Wl,--out-implib,libcmTC_a5ba6.dll.a -Wl,--major-image-version,0,--minor-image-version,0
    D:/msys64/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld.exe: unrecognized option '--enable-auto-import'
    D:/msys64/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/13.2.0/../../../../aarch64-none-elf/bin/ld.exe: use the --help option for usage information
    collect2.exe: error: ld returned 1 exit status
    make[4]: *** [CMakeFiles/cmTC_a5ba6.dir/build.make:99: cmTC_a5ba6.exe] Error 1
    make[4]: Saindo do diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

    make[3]: *** [Makefile:127: cmTC_a5ba6/fast] Error 2
    make[3]: Saindo do diretório '/home/joao2/Downloads/grok-11.0.0/build-switch/thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-build/CMakeFiles/CMakeScratch/TryCompile-zNPq5v'

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!
make[2]: *** [thirdparty/CMakeFiles/libjpeg-turbo.dir/build.make:92: thirdparty/libjpeg-turbo-prefix/src/libjpeg-turbo-stamp/libjpeg-turbo-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:514: thirdparty/CMakeFiles/libjpeg-turbo.dir/all] Error 2
make: *** [Makefile:156: all] Error 2````
OS: Windows 10 64-bit, MSYS2 with the devKitPro repositories & environment
Version of **grok**: 11.0.0

**Comment by boxerab** [comment]
You can disable jpeg build by adding `-DGRK_BUILD_JPEG=OFF`

**Comment by MrBolt2005** [comment]
Is there somehow else I can try to fix the compiler test error?  ~

**Comment by boxerab** [comment]
Yes, you can clone the repo instead of downloading the tarball. Then you can run the tests (but you also need to download test data). Here is [more info](https://github.com/GrokImageCompression/grok/wiki/4.-Conformance-and-Regression-Testing)
