### ISSUE TITLE
Avoid purging tags and Git history

### ISSUE THREAD

**Issue by sanks02** [GrokImageCompression/grok#356]
### What happened?

Hey,

I noticed that the 10.0.8 tag has been removed when my build process suddenly started failing with this error:

```
git clone --branch v10.0.8 --depth 1 https://github.com/GrokImageCompression/grok.git .:
1.069 Cloning into '.'...
1.795 warning: Could not find remote branch v10.0.8 to clone.
1.797 fatal: Remote branch v10.0.8 not found in upstream origin
```

I haven't had a chance to upgrade yet because [libgen](https://github.com/olbat/libgen) doesn't work with Grok 11 (generated bindings are incorrect).

I looked into the Git history, but it was purged as well:

![image](https://github.com/GrokImageCompression/grok/assets/41530422/d809e221-2707-4742-923d-f54e43b146a4)

Is it possible to restore the 10.0.8 tag and keep old tags in the future?

**Comment by boxerab** [comment]
The library has been re-organized - apologies for the inconvenience !
