### ISSUE TITLE
Missing previous releases (<= 11.0.0) 

### ISSUE THREAD

**Issue by ksclarke** [GrokImageCompression/grok#358]
### Contact Details

ksclarke@ksclarke.io

### What happened?

The previous releases have disappeared from the GitHub project page (along with the GitHub history being wiped out, leaving just a "day one" commit). Are there plans to make the previous code/releases available?

### Version

11.0.0

### Operating System

Linux

### Relevant log output

```shell
N/A
```

**Comment by boxerab** [comment]
> Are there plans to make the previous code/releases available?

I'm afraid previous code and releases will not be available.

**Comment by boxerab** [comment]
I have added a note in the README about the recent project re-organization.
