### ISSUE TITLE
[Bug]: Build fails unless `ninja libjpeg-turbo` is explicitly built first

### ISSUE THREAD

**Issue by nico** [GrokImageCompression/grok#359]
### What happened?

```sh
git clone https://github.com/GrokImageCompression/grok.git
cd grok
mkdir build
cd build
cmake -GNinja ..
ninja
```

### Version

Latest commit (8254cca46e8cdc37137).

(…why does this repo have only two commits, with the first adding everyone? That looks a bit sus.)

### Operating System

macOS

### Relevant log output

```shell
ninja: error: 'thirdparty/bin/libjpeg.a', needed by 'bin/libgrokj2kcodec.12.0.0.dylib', missing and no known rule to make it
```

If I manually run `ninja libjpeg-turbo` and then `ninja`, it works.

This is probably missing a dependency from somewhere on the `libjpeg-turbo` target.

(By the way, it's very neat how grok downloads all its deps!)

**Comment by boxerab** [comment]
See #353 for details on dependency issue. We don't have plans to support `ninja`.
