### ISSUE TITLE
Segfault when decoding region

### ISSUE THREAD

**Issue by drtimes** [GrokImageCompression/grok#53]
Hi,

Segfault occurs when decoding a region with coordinates x0,y0,x1,y1, where x0 or y0 is the size of tile minus one. Error reproduces for Sentinel-2 images of different resolutions and tile size.

`./opj_decompress -i /home/user/Sentinel2/36-U-XU-2016-5-2-0/B01.jp2 -d 191,191,1090,1090 -NumThreads 1 -o tile.tif`

Plugin ./libopenjp2_plugin.so loaded
Full library path: ./libopenjp2_plugin.so
Loaded plugin has been registered
Plugin ./libopenjp2_plugin.so initialized 

[INFO] Start to read j2k main header (1927).
[INFO] Main header has been correctly decoded.
[INFO] Setting decoding area to 191,191,1090,1090
[INFO] Header of tile 1 / 100 has been read.
*** Error in `./opj_decompress': free(): invalid next size (fast): 0x00007f0100000a70 ***
Aborted (core dumped)

Best regards,
Kate

**Comment by boxerab** [comment]
Hi Kate,

Thanks for reporting this issue.  I haven't tested this kind of edge case - should have a fix shortly.
Aaron

**Comment by boxerab** [comment]
Can you please provide a link to the sentinel2 file that you used ?

**Comment by boxerab** [comment]
Also, is the original image lossy or lossless compressed ?

**Comment by boxerab** [comment]
Don't worry about Sentinel 2 image -  I have reproduced this bug for lossy-encoded image.

**Comment by boxerab** [comment]
I have fixed a number of issues with region decode : if you have time, please pull the latest
and see if this fixes your issue. Thanks.

**Comment by boxerab** [comment]
I am closing this one. Please re-open if problem persists.

**Comment by drtimes** [comment]
It did fixed the issue. Thanks!
