### ISSUE TITLE
Decode: Custom image data type

### ISSUE THREAD

**Issue by novalain** [GrokImageCompression/grok#82]
The decoded data in an `opj_image_comp` is always of type `int_32t`. It would be great if the type here could be specified to, for example, `unsigned char`. Sometimes the precision of the image to decode is known beforehand, and in those cases it's extra work for the client to do the conversion and the library also uses more memory than needed.

**Comment by boxerab** [comment]
Thanks, Michael. I will look into this. One thing to keep in mind is that internally, the library uses 32 bit fixed point to decode the image.  So, we do need to allocate an `int_32t` . But, it is possible that we are allocating two 32 bit buffers for 8 bit data, so this would be a waste.

**Comment by boxerab** [comment]
So, it looks like this is already optimized - for single tile decode, we only allocate a single 32 bit buffer. One enhancement we could do is compact the data in the library so that if it is 8 bit, it will only occupy the 1/4 of the buffer.

**Comment by boxerab** [comment]
I'm afraid this issue is going to be low priority - there are a number of more pressing issues that need to be addressed in the library.  Closing.
