### ISSUE TITLE
Grok cannot compile on CentOS 7

### ISSUE THREAD

**Issue by martinhankovec** [GrokImageCompression/grok#95]
Hello,
Grok cannot be compiled on CentOS 7 (gcc 4.8.5) due to use of PRIi64 and PRId64 macros in fprintf. I have replaced these macros by %d, but compiler complains about bad variables type (but can be compiled with warnings now).
Can You please take a look at it?
With best regards
Martin

**Comment by boxerab** [comment]
Thanks, Martin. I will take a look.

**Comment by boxerab** [comment]
Since the project supports C++14, we can't support very old versions of gcc,, but we should be able to get it working with 4.8.5

**Comment by boxerab** [comment]
GCC 4.8.5 is now supported. Closing.
