### ISSUE TITLE
Build failure on macOS 10.12.6 (cmake 3.9.0)

### ISSUE THREAD

**Issue by ff-afarm** [GrokImageCompression/grok#99]
When attempting to build Grok with the instructions in INSTALL.md, the build failed with errors.
To build, I entered the commands in INSTALL.md:
`cmake .`
`make install`
cmake completes successfully, but then make fails with the following errors:

    Scanning dependencies of target opj_dump
    [ 66%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/opj_dump.cpp.o
    [ 67%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/convert.cpp.o
    [ 67%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/ImageFormat.cpp.o
    [ 68%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/PNMFormat.cpp.o
    [ 69%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/PGXFormat.cpp.o
    [ 70%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/BMPFormat.cpp.o
    [ 71%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/TGAFormat.cpp.o
    [ 72%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/RAWFormat.cpp.o
    [ 72%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/__/common/color.cpp.o
    [ 73%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/__/common/grok_getopt.cpp.o
    [ 74%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/TIFFFormat.cpp.o
    [ 75%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/PNGFormat.cpp.o
    [ 76%] Building CXX object src/bin/jp2/CMakeFiles/opj_dump.dir/JPEGFormat.cpp.o
    /Users/afarm/Downloads/grok-master/src/bin/jp2/JPEGFormat.cpp:315:2: error: no
          matching function for call to 'jpeg_set_quality'
            jpeg_set_quality(&cinfo,
            ^~~~~~~~~~~~~~~~
    /usr/local/include/jpeglib.h:991:14: note: candidate function not viable: no
          known conversion from 'bool' to 'boolean' for 3rd argument
    EXTERN(void) jpeg_set_quality JPP((j_compress_ptr cinfo, int quality,
                 ^
    /Users/afarm/Downloads/grok-master/src/bin/jp2/JPEGFormat.cpp:324:2: error: no
          matching function for call to 'jpeg_start_compress'
            jpeg_start_compress(&cinfo, true);
            ^~~~~~~~~~~~~~~~~~~
    /usr/local/include/jpeglib.h:1010:14: note: candidate function not viable: no
          known conversion from 'bool' to 'boolean' for 2nd argument
    EXTERN(void) jpeg_start_compress JPP((j_compress_ptr cinfo,
                 ^
    2 errors generated.
    make[2]: *** [src/bin/jp2/CMakeFiles/opj_dump.dir/JPEGFormat.cpp.o] Error 1
    make[1]: *** [src/bin/jp2/CMakeFiles/opj_dump.dir/all] Error 2
    make: *** [all] Error 2

**Comment by boxerab** [comment]
Thanks for reporting. This is now fixed in master.

**Comment by ff-afarm** [comment]
Thanks very much. Unfortunately, this didn't fix the build, but I've created a pull request (#100) which seems to fix it.

**Comment by boxerab** [comment]
Picky compiler! Thanks for the PR : since fix was so small, I just made a manual commit.
